<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.54">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sujean Gallego">
<meta name="dcterms.date" content="2024-07-31">
<meta name="description" content="examining graphic novels">

<title>The Recipe to an Adaptation Blog Post – myblog</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">myblog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">The Recipe to an Adaptation Blog Post</h1>
                  <div>
        <div class="description">
          examining graphic novels
        </div>
      </div>
                </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Sujean Gallego </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">July 31, 2024</p>
      </div>
    </div>
    
      <div>
      <div class="quarto-title-meta-heading">Modified</div>
      <div class="quarto-title-meta-contents">
        <p class="date-modified">July 30, 2024</p>
      </div>
    </div>
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="the-recipe-to-an-adaptation" class="level1">
<h1>The Recipe to an Adaptation</h1>
<section id="resarch-by-sujean-gallego" class="level3">
<h3 class="anchored" data-anchor-id="resarch-by-sujean-gallego">Resarch by Sujean Gallego</h3>
<section id="july-31-2024" class="level4">
<h4 class="anchored" data-anchor-id="july-31-2024">July 31, 2024</h4>
</section>
</section>
</section>
<section id="i.-introduction" class="level1">
<h1>I. INTRODUCTION</h1>
<section id="an-overview" class="level2">
<h2 class="anchored" data-anchor-id="an-overview">1. An Overview</h2>
<p><em>adaptation – the action or process of adapting or being adapted.</em></p>
<p>Or a term to describe a piece of media, usually a television show or movie, that is based on pre-existing work, usually literary or theatrical work.</p>
<p>This type of work is very common, so much so that the Oscars even has a category “Best Adapted Screenplay.” Some of the films that won include: - <em>The Godfather (1972)</em> - <em>L.A. Confidential (1997)</em> - <em>The Lord of the Rings: Return of the King (2003)</em> - <em>The Social Network (2010)</em> - <em>Moonlight (2016)</em></p>
<p>Some recognizable titles also include: - <em>The Color Purple (1985)</em> - <em>Shrek (2001)</em> - <em>Game of Thrones (2011)</em> - <em>The Handmaid’s Tale (2017)</em> - <em>The Last of Us (2023)</em> - <em>Oppenheimer (2023)</em></p>
<p>And there is so much more!</p>
<p>Quickly scrolling through the list of winners in this category on Wikipedia, I noticed that most of these adaptations are based on <strong>novels</strong>. Very few were theatrical plays, musicals, and, especially, graphic novels. Of course, this could just be due to the fact that I was looking through a list of Oscar nominees. Maybe the Oscars don’t value adaptations based off of graphic novels. Or maybe the quality of adaptations that were made based on graphic novels were never good enough to gain an Oscar nomination. Or maybe there is just a lack of graphic novels in the literary space to begin with.</p>
<p>World renowned director Martin Scorscese once said, “I don’t think [Marvel movies are] cinema” (Connell). Marvel movies are all adapted works based on graphic novels, specifically in the superhero genre. Now that is a whole different conversation that can be very dividing. Something that I will not be delving into in this project. Nonetheless, this shows how graphic novels as a type of work are largely looked down upon. And this doesn’t just end at the lack of adaptations, this is also seen in literary space as well. They are often looked down upon as a lesser form of literature for their lack of text, abundance of pictures, and themes, which are usually superhero-based (Mwissell). People view them congruent to children’s books, which are less text and picture-based, and therefore view graphic novels work targeted towards children, incapable of revealing deeper meanings and insights to life as novels do.</p>
<p>Now the opposite is seen internationally. Countries such as Japan and South Korea are well known for their adaptations of graphic novels in the media space, and actually seem to be the preferred form of entertainment. Mangas (Japanese graphic novels) have become a major driving force in Japan’s economy (Luster) and top source for adaptations in Japanese entertainment, especially in anime. While not to the same extent, manhwas (South Korean graphic novels) have also been a relevant part of South Korean culture and media. Korean dramas such as The Princess Hours and Boys Over Flowers are examples of Korean entertainment adapted from graphic novels that have accumulated a large cultural significance and an iconic status. Like Japan, South Korean Webtoons—digitally published comics and graphic novels—have become the top source of adaptations for Korean Dramas. It seems much easier to adapt: storyboards are already laid out, a couple of changes can be made to suit the director, the script is basically all written. So…</p>
<p>Why aren’t we seeing the same trend in the United States? Is it really American pride and stigma preventing these graphic novels from receiving an adaptation?</p>
<p>Maybe not…? One example can be seen in Nick Drnasno’s Sabrina, published in 2018, which became the first ever graphic novel to be longlisted for the Booker Prize, a highly prestigious literary award that is selected from a longlist and shortlist of nominees every year (NewStatesman). Winning the Booker Prize basically means that said-book is the “best single work” published in said-year. And being nominated is a great achievement in itself. Sabrina was praised for its mature themes relevant to today’s society which was only elevated by its drawings and visual style (Park). Similar sentiments were met with the graphic novel Persepolis by Marjane Satrapi, which did get an animated feature adaptation in 2007. The film by the same name was also met with great critical acclaim receiving a 97% score on RottenTomatoes (RottenTomatoes).</p>
</section>
<section id="the-question" class="level2">
<h2 class="anchored" data-anchor-id="the-question">2. The Question</h2>
<p>With so many outside factors it’s hard to determine why graphic novels aren’t more adapted in today’s society. But maybe the books themselves can reveal traits or characteristics that may shed some light on what makes a good graphic novel for adaptation. In this project, I use data from the Graphic Narrative Corpus, to answer the question:</p>
<p><strong><em>What makes a good graphic novel for adaptation? or What is the recipe for scoring an adaptation as a graphic novel?</em></strong></p>
</section>
<section id="about-the-data" class="level2">
<h2 class="anchored" data-anchor-id="about-the-data">3. About the Data</h2>
<p>The data was collected by literary scholars and computer and cognitive scientists at Potsdam and Paderborn universities for a research project, funded by the German Federal Ministry of Education and Research. A total of 253 titles published in the United States, Great Britain, Canada, and India are included in the dataset. Requirements for inclusion were that novels had to be written in English, exceed 64 pages in length, tell one continuous story, target an adult audience and form one single volume or a limited series. Both nonfiction and fictional texts are included in the data, with a vast variety of genres. The project ran from 2014-2020, but includes texts published from the mid-70s to 2017, garnered through various types of collections such as academic databases, library collections, and online lists and bibliographies (cite). The GNC has a total of 20 tables [<em>Adaptation, Author, Book, Book Genre, Country, Ethnicity, Format, Gender, Genre, GNSource, Issue, Language, Place, Publisher, RelBookAuthor, RelBookIllustrator, Source, SourceCategory, SelectionSource,Translation</em>] each coming as their own .csv file. It was noted that because they used a “cheap” data GUI, they referred to the book title rather than the ID. In addition, a “Scheme” PDF file was given which lists brief information about each table and their respective variables, however, the table Book Genre was not listed in the pdf, it was only seen briefly in their Corpus Graph visualization. Some of the tables provided were simply selection sources–<em>or listed options/codes</em>–for columns in other variables. Thus, the tables used in this project were not “selection sources” and selected based on their importance in answering the research question. Specifically, we used the tables: - Adaptation, represented different adaptations (like movie, tv series, novel…) of graphic novels. - Author, information on the authors and illustrators. - Book, main table, contains the information on the books. - Book Genre, provides the genres for each of the books. - RelBookAuthor, junction table to represent the n:m relationship between the book and its authors. - Issue, represents the different issues published for a book.</p>
<p>Link: https://groups.uni-paderborn.de/graphic-literature/gncorpus/corpus.php</p>
</section>
</section>
<section id="ii.-methods" class="level1">
<h1>II. METHODS</h1>
<div id="db2fa69a" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="importing-data" class="level2">
<h2 class="anchored" data-anchor-id="importing-data">1. Importing Data</h2>
<p>We begin by imporing the data from the github repository connected to this notebook:</p>
<div id="bc1439d5" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>graphic_novels <span class="op">=</span> pd.read_csv(<span class="st">'https://raw.githubusercontent.com/sujean8222/GraphicNovels/main/Book.csv'</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>adaptations <span class="op">=</span> pd.read_csv(<span class="st">'https://raw.githubusercontent.com/sujean8222/GraphicNovels/main/Adaptation.csv'</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>authors <span class="op">=</span> pd.read_csv(<span class="st">'https://raw.githubusercontent.com/sujean8222/GraphicNovels/main/Author.csv'</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>book_genres <span class="op">=</span> pd.read_csv(<span class="st">'https://raw.githubusercontent.com/sujean8222/GraphicNovels/main/BookGenre.csv'</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>issue <span class="op">=</span> pd.read_csv(<span class="st">'https://raw.githubusercontent.com/sujean8222/GraphicNovels/main/Issue.csv'</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>rel_book_author <span class="op">=</span> pd.read_csv(<span class="st">'https://raw.githubusercontent.com/sujean8222/GraphicNovels/main/RelBookAuthor.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="cleaning-and-organizing-data" class="level2">
<h2 class="anchored" data-anchor-id="cleaning-and-organizing-data">2. Cleaning and Organizing Data</h2>
<section id="a.-inspecting-the-rawdata" class="level3">
<h3 class="anchored" data-anchor-id="a.-inspecting-the-rawdata">a. Inspecting the RawData</h3>
<p>With the data imported, we look at the first few lines of data to see what we’re working with:</p>
<div id="4c96a34b" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>graphic_novels.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">7 Miles A Second</th>
<th data-quarto-table-cell-role="th">1</th>
<th data-quarto-table-cell-role="th">Autobiography</th>
<th data-quarto-table-cell-role="th">5/1/96</th>
<th data-quarto-table-cell-role="th">7 Miles A Second.jpg</th>
<th data-quarto-table-cell-role="th">English</th>
<th data-quarto-table-cell-role="th">0.1</th>
<th data-quarto-table-cell-role="th">search.proquest.com</th>
<th data-quarto-table-cell-role="th">colour</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">978-1-60699-614-0</th>
<th data-quarto-table-cell-role="th">7_Miles_A_Second</th>
<th data-quarto-table-cell-role="th">4.01</th>
<th data-quarto-table-cell-role="th">382</th>
<th data-quarto-table-cell-role="th">7 Miles A Second.1</th>
<th data-quarto-table-cell-role="th">0.6</th>
<th data-quarto-table-cell-role="th">0.5</th>
<th data-quarto-table-cell-role="th">0.5.1</th>
<th data-quarto-table-cell-role="th">Unnamed: 21</th>
<th data-quarto-table-cell-role="th">Paderborn</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1</td>
<td>A Contract With God</td>
<td>31</td>
<td>NaN</td>
<td>1/1/78</td>
<td>A Contract with God.png</td>
<td>English</td>
<td>0</td>
<td>rollingstone.com</td>
<td>--&gt; black&amp;white</td>
<td>...</td>
<td>978-0-393-32804-2</td>
<td>A_Contract_With_God</td>
<td>4.07</td>
<td>9146</td>
<td>A Contract With God</td>
<td>0.0</td>
<td>NaN</td>
<td>1.0</td>
<td>NaN</td>
<td>Paderborn</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2</td>
<td>A Drifting Life</td>
<td>8</td>
<td>NaN</td>
<td>11/20/08</td>
<td>A Drifting LIfe.jpg</td>
<td>Japanese</td>
<td>0</td>
<td>101 Outstanding Graphic Novels by Stephen Weiner</td>
<td>--&gt; black&amp;white</td>
<td>...</td>
<td>978-1-897299-74-6</td>
<td>A_Drifting_Life</td>
<td>4.00</td>
<td>2404</td>
<td>Gekiga Hy\u014dry\u016b</td>
<td>0.0</td>
<td>1.0</td>
<td>NaN</td>
<td>NaN</td>
<td>Bielefeld</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>3</td>
<td>A Small Killing</td>
<td>5</td>
<td>NaN</td>
<td>10/3/91</td>
<td>A Small Killing.JPG</td>
<td>English</td>
<td>0</td>
<td>Amazon.com bestselling graphic novels</td>
<td>colour</td>
<td>...</td>
<td>1-59291-009-0</td>
<td>A_Small_Killing</td>
<td>3.40</td>
<td>731</td>
<td>A Small Killing</td>
<td>0.0</td>
<td>NaN</td>
<td>1.0</td>
<td>NaN</td>
<td>Bielefeld</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>4</td>
<td>Tale of Sand</td>
<td>0</td>
<td>NaN</td>
<td>12/14/11</td>
<td>Tale of Sand.jpg</td>
<td>English</td>
<td>0</td>
<td>en.wikipedia.org/wiki/List_of_Harvey_Award_win...</td>
<td>colour</td>
<td>...</td>
<td>978-1-936393-09-1</td>
<td>Tale_of_Sand</td>
<td>3.78</td>
<td>2386</td>
<td>Tale of Sand</td>
<td>1.0</td>
<td>NaN</td>
<td>1.0</td>
<td>NaN</td>
<td>Bielefeld</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>5</td>
<td>Absolute Justice</td>
<td>0</td>
<td>NaN</td>
<td>11/17/09</td>
<td>Absolute Justice.jpg</td>
<td>English</td>
<td>1</td>
<td>Amazon.com bestselling graphic novels</td>
<td>colour</td>
<td>...</td>
<td>978-1-4012-3526-0</td>
<td>Absolute_Justice</td>
<td>4.17</td>
<td>1228</td>
<td>Absolute Justice</td>
<td>0.0</td>
<td>NaN</td>
<td>1.0</td>
<td>NaN</td>
<td>Paderborn</td>
</tr>
</tbody>
</table>

<p>5 rows × 23 columns</p>
</div>
</div>
</div>
<p>The original data did not provide column titles, which will be harder to navigate when analyzing the data through python, so we begin data clean-up by adding column names for the rest of the data. In addition, there are a couple of columns not listed in the given “Scheme” PDF file. It is unclear what they are referring to so we will delete those columns from the dataframe.</p>
<div id="5b47d52a" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>graphic_novels.columns <span class="op">=</span> [<span class="st">'ID'</span>, <span class="st">'Title'</span>, <span class="st">'Mentions'</span>, <span class="st">'Unclear'</span>, <span class="st">'Date Published'</span>, <span class="st">'Image'</span>, <span class="st">'Original Language'</span>, <span class="st">'Foreign Key'</span>,<span class="st">'GN_Source'</span>, <span class="st">'color_type'</span>, <span class="st">'Limited Series'</span>, <span class="st">'Book Series'</span>, <span class="st">'Unlimited Series'</span>, <span class="st">'ISBN'</span>, <span class="st">'Directory'</span>,<span class="st">'Avg Rating'</span>, <span class="st">'Number of Ratings'</span>, <span class="st">'Original Title'</span>, <span class="st">'Unlisted'</span>, <span class="st">'Unlisted'</span>, <span class="st">'Unlisted'</span>, <span class="st">'Unlisted'</span>, <span class="st">'University'</span>]</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>adaptations.columns <span class="op">=</span> [<span class="st">'ID'</span>, <span class="st">'BookID'</span>, <span class="st">'Type'</span>, <span class="st">'Title'</span>, <span class="st">'Publication'</span>]</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>authors.columns <span class="op">=</span> [<span class="st">'ID'</span>, <span class="st">'FirstName'</span>, <span class="st">'LastName'</span>, <span class="st">'Gender_ID'</span>, <span class="st">'CountryOfOriginID'</span>, <span class="st">'CountryOfResidence'</span>, <span class="st">'DateOfDeath'</span>, <span class="st">'DateOfBirth'</span>, <span class="st">'Ethnicity'</span>, <span class="st">'PenName'</span>]</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>book_genres.columns <span class="op">=</span> [<span class="st">'ID'</span>, <span class="st">'BookID'</span>, <span class="st">'SourceID'</span>, <span class="st">'GenreID'</span>, <span class="st">'isMain'</span>]</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>issue.columns <span class="op">=</span> [<span class="st">'ID'</span>, <span class="st">'FormatID'</span>, <span class="st">'Edition'</span>, <span class="st">'BookID'</span>, <span class="st">'LanguageID'</span>, <span class="st">'Mentions'</span>, <span class="st">'Pages'</span>, <span class="st">'PlaceOfPublicationID'</span>, <span class="st">'PublisherID'</span>, <span class="st">'Delete'</span>, <span class="st">'Date'</span>, <span class="st">'Width'</span>, <span class="st">'Depth'</span>, <span class="st">'Height'</span>, <span class="st">'Unit'</span>]</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>rel_book_author.columns <span class="op">=</span> [<span class="st">'ID'</span>, <span class="st">'BookID'</span>, <span class="st">'AuthorID'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="3f8728a9" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>graphic_novels.drop(columns<span class="op">=</span>[<span class="st">'Unclear'</span>, <span class="st">'Unlisted'</span>, <span class="st">'Unlisted'</span>, <span class="st">'Unlisted'</span>, <span class="st">'Unlisted'</span>, <span class="st">'University'</span>], inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>issue.drop(columns<span class="op">=</span><span class="st">'Delete'</span>, inplace <span class="op">=</span> <span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="b.-describing-dataframes-and-filling-in-relevant-missing-values" class="level3">
<h3 class="anchored" data-anchor-id="b.-describing-dataframes-and-filling-in-relevant-missing-values">b. Describing Dataframes and Filling in Relevant Missing Values</h3>
<p>Now that the columns are named, we describe the different dataframes to gain further information about what they are made up of and if there are any missing values that need to be filled. That way we will have an even amount of values to use in other functions.</p>
<section id="adaptations-dataframe" class="level4">
<h4 class="anchored" data-anchor-id="adaptations-dataframe"><em>adaptations DataFrame</em></h4>
<div id="c1ed3241" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>adaptations.describe(include<span class="op">=</span><span class="st">'all'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">ID</th>
<th data-quarto-table-cell-role="th">BookID</th>
<th data-quarto-table-cell-role="th">Type</th>
<th data-quarto-table-cell-role="th">Title</th>
<th data-quarto-table-cell-role="th">Publication</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>69.000000</td>
<td>69.000000</td>
<td>66</td>
<td>66</td>
<td>64</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">unique</td>
<td>NaN</td>
<td>NaN</td>
<td>49</td>
<td>59</td>
<td>58</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">top</td>
<td>NaN</td>
<td>NaN</td>
<td>Film</td>
<td>Barefoot Gen</td>
<td>1972-01-01</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">freq</td>
<td>NaN</td>
<td>NaN</td>
<td>10</td>
<td>4</td>
<td>4</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">mean</td>
<td>52.666667</td>
<td>138.347826</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">std</td>
<td>25.236917</td>
<td>102.459723</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">min</td>
<td>2.000000</td>
<td>5.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">25%</td>
<td>38.000000</td>
<td>57.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">50%</td>
<td>55.000000</td>
<td>117.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">75%</td>
<td>73.000000</td>
<td>229.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">max</td>
<td>91.000000</td>
<td>312.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Adaptations seems to be missing some values in ‘Type’, ‘Title’, and ‘Publication’. To find the rows that are missing values we use indexing:</p>
<div id="00ede060" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>adaptations[adaptations.isnull().<span class="bu">any</span>(axis<span class="op">=</span><span class="dv">1</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">ID</th>
<th data-quarto-table-cell-role="th">BookID</th>
<th data-quarto-table-cell-role="th">Type</th>
<th data-quarto-table-cell-role="th">Title</th>
<th data-quarto-table-cell-role="th">Publication</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">17</td>
<td>38</td>
<td>132</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">18</td>
<td>39</td>
<td>144</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">24</td>
<td>45</td>
<td>266</td>
<td>Minisiries of animated films</td>
<td>Bone</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">42</td>
<td>64</td>
<td>148</td>
<td>Play</td>
<td>The Tragical Comedy or Comical Tragedy of Mr. ...</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">55</td>
<td>77</td>
<td>284</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Because of the way the dataframes were constructed, we need to refer to another dataframe to find the name of the book. Specfically, we use indexing in the dataframe <strong>graphic_novels</strong>, putting the ‘BookID’ of <strong>adaptations</strong> in graphic_novel’s ‘ID’. With the title we can look up the missing information on google and fill in the missing values.</p>
<div id="f8a5c21d" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>graphic_novels[graphic_novels[<span class="st">'ID'</span>] <span class="op">==</span> <span class="dv">219</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">ID</th>
<th data-quarto-table-cell-role="th">Title</th>
<th data-quarto-table-cell-role="th">Mentions</th>
<th data-quarto-table-cell-role="th">Date Published</th>
<th data-quarto-table-cell-role="th">Image</th>
<th data-quarto-table-cell-role="th">Original Language</th>
<th data-quarto-table-cell-role="th">Foreign Key</th>
<th data-quarto-table-cell-role="th">GN_Source</th>
<th data-quarto-table-cell-role="th">color_type</th>
<th data-quarto-table-cell-role="th">Limited Series</th>
<th data-quarto-table-cell-role="th">Book Series</th>
<th data-quarto-table-cell-role="th">Unlimited Series</th>
<th data-quarto-table-cell-role="th">ISBN</th>
<th data-quarto-table-cell-role="th">Directory</th>
<th data-quarto-table-cell-role="th">Avg Rating</th>
<th data-quarto-table-cell-role="th">Number of Ratings</th>
<th data-quarto-table-cell-role="th">Original Title</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">179</td>
<td>219</td>
<td>A History of Violence</td>
<td>7</td>
<td>1/1/97</td>
<td>A History of Violence.jpg</td>
<td>English</td>
<td>0</td>
<td>JSTOR</td>
<td>--&gt; black&amp;white</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>978-1-4012-3189-7</td>
<td>A_History_of_Violence</td>
<td>3.45</td>
<td>2060</td>
<td>A History of Violence</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="0228133a" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>adaptations.loc[<span class="dv">17</span>, [<span class="st">'Type'</span>, <span class="st">'Title'</span>, <span class="st">'Publication'</span>]] <span class="op">=</span> [<span class="st">'Television series'</span>, <span class="st">'Games Of Thrones'</span>, <span class="st">'2011-04-17'</span>]</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>adaptations.loc[<span class="dv">18</span>, [<span class="st">'Type'</span>, <span class="st">'Title'</span>, <span class="st">'Publication'</span>]] <span class="op">=</span> [<span class="st">'Television series'</span>, <span class="st">'Games Of Thrones'</span>, <span class="st">'2011-04-17'</span>]</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>adaptations.loc[<span class="dv">24</span>, <span class="st">'Publication'</span>] <span class="op">=</span> <span class="st">'Never Published'</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>adaptations.loc[<span class="dv">42</span>, <span class="st">'Publication'</span>] <span class="op">=</span> <span class="st">'Never Published'</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>adaptations.loc[<span class="dv">55</span>, [<span class="st">'Type'</span>, <span class="st">'Title'</span>, <span class="st">'Publication'</span>]] <span class="op">=</span> [<span class="st">'Feature film'</span>, <span class="st">'Kakera'</span>, <span class="st">'2010-04-03'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Unexpectedly, while doing research it was found that one of the adaptations was cancelled and never went into production, so we dropped it.</p>
<div id="3376e9c8" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>adaptations <span class="op">=</span> adaptations.drop(index<span class="op">=</span>[<span class="dv">24</span>, <span class="dv">42</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="rel_book_author-dataframe" class="level4">
<h4 class="anchored" data-anchor-id="rel_book_author-dataframe"><em>rel_book_author DataFrame</em></h4>
<div id="bbcb5f9b" class="cell" data-scrolled="true" data-execution_count="11">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>rel_book_author.describe(include<span class="op">=</span><span class="st">'all'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">ID</th>
<th data-quarto-table-cell-role="th">BookID</th>
<th data-quarto-table-cell-role="th">AuthorID</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>287.000000</td>
<td>287.000000</td>
<td>279.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mean</td>
<td>206.397213</td>
<td>156.637631</td>
<td>136.853047</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">std</td>
<td>105.920750</td>
<td>92.720392</td>
<td>114.200080</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">min</td>
<td>22.000000</td>
<td>1.000000</td>
<td>1.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25%</td>
<td>116.500000</td>
<td>77.500000</td>
<td>42.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">50%</td>
<td>213.000000</td>
<td>158.000000</td>
<td>104.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">75%</td>
<td>292.500000</td>
<td>237.500000</td>
<td>227.500000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">max</td>
<td>391.000000</td>
<td>335.000000</td>
<td>446.000000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="a690c945" class="cell" data-scrolled="true" data-execution_count="12">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>rel_book_author[rel_book_author.isnull().<span class="bu">any</span>(axis<span class="op">=</span><span class="dv">1</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">ID</th>
<th data-quarto-table-cell-role="th">BookID</th>
<th data-quarto-table-cell-role="th">AuthorID</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">26</td>
<td>56</td>
<td>28</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">48</td>
<td>85</td>
<td>52</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">128</td>
<td>189</td>
<td>152</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">132</td>
<td>196</td>
<td>5</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">133</td>
<td>197</td>
<td>48</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">154</td>
<td>226</td>
<td>174</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">219</td>
<td>299</td>
<td>245</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">220</td>
<td>300</td>
<td>245</td>
<td>NaN</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>We look for the missing AuthorIDs by searching the <strong>graphic_novels dataframe</strong> for ‘BookID’s and then looking up the authors on the internet. We then look up their last name in the <strong>authors dataframe</strong> to find the ’AuthorID’ listed as ‘ID’. We input those values into the missing values.</p>
<div id="d3014cf5" class="cell" data-scrolled="true" data-execution_count="13">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>authors[authors[<span class="st">'LastName'</span>] <span class="op">==</span> <span class="st">'Rusnak'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">ID</th>
<th data-quarto-table-cell-role="th">FirstName</th>
<th data-quarto-table-cell-role="th">LastName</th>
<th data-quarto-table-cell-role="th">Gender_ID</th>
<th data-quarto-table-cell-role="th">CountryOfOriginID</th>
<th data-quarto-table-cell-role="th">CountryOfResidence</th>
<th data-quarto-table-cell-role="th">DateOfDeath</th>
<th data-quarto-table-cell-role="th">DateOfBirth</th>
<th data-quarto-table-cell-role="th">Ethnicity</th>
<th data-quarto-table-cell-role="th">PenName</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">306</td>
<td>397</td>
<td>Karl</td>
<td>Rusnak</td>
<td>1.0</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="78a0aa62" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>rel_book_author.loc[<span class="dv">26</span>, <span class="st">'AuthorID'</span>] <span class="op">=</span> <span class="dv">61</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>rel_book_author.loc[<span class="dv">48</span>, <span class="st">'AuthorID'</span>] <span class="op">=</span> <span class="dv">122</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>rel_book_author.loc[<span class="dv">128</span>, <span class="st">'AuthorID'</span>] <span class="op">=</span> <span class="dv">64</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>rel_book_author.loc[<span class="dv">132</span>, <span class="st">'AuthorID'</span>] <span class="op">=</span> <span class="dv">7</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>rel_book_author.loc[<span class="dv">133</span>, <span class="st">'AuthorID'</span>] <span class="op">=</span> <span class="dv">29</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>rel_book_author.loc[<span class="dv">154</span>, <span class="st">'AuthorID'</span>] <span class="op">=</span> <span class="dv">11</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>rel_book_author.loc[<span class="dv">219</span>, <span class="st">'AuthorID'</span>] <span class="op">=</span> <span class="dv">396</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>rel_book_author.loc[<span class="dv">220</span>, <span class="st">'AuthorID'</span>] <span class="op">=</span> <span class="dv">397</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="authors-dataframe" class="level4">
<h4 class="anchored" data-anchor-id="authors-dataframe"><em>authors DataFrame</em></h4>
<div id="04795c6c" class="cell" data-scrolled="true" data-execution_count="15">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>authors.describe(include<span class="op">=</span><span class="st">'all'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">ID</th>
<th data-quarto-table-cell-role="th">FirstName</th>
<th data-quarto-table-cell-role="th">LastName</th>
<th data-quarto-table-cell-role="th">Gender_ID</th>
<th data-quarto-table-cell-role="th">CountryOfOriginID</th>
<th data-quarto-table-cell-role="th">CountryOfResidence</th>
<th data-quarto-table-cell-role="th">DateOfDeath</th>
<th data-quarto-table-cell-role="th">DateOfBirth</th>
<th data-quarto-table-cell-role="th">Ethnicity</th>
<th data-quarto-table-cell-role="th">PenName</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>351.000000</td>
<td>351</td>
<td>351</td>
<td>346.000000</td>
<td>311</td>
<td>289</td>
<td>25</td>
<td>261</td>
<td>325</td>
<td>63</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">unique</td>
<td>NaN</td>
<td>311</td>
<td>338</td>
<td>NaN</td>
<td>37</td>
<td>22</td>
<td>25</td>
<td>234</td>
<td>8</td>
<td>63</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">top</td>
<td>NaN</td>
<td>Paul</td>
<td>Davis</td>
<td>NaN</td>
<td>USA</td>
<td>USA</td>
<td>2005-01-03</td>
<td>1965-01-01</td>
<td>White</td>
<td>Will Eisner Maxwell, Will Eisner</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">freq</td>
<td>NaN</td>
<td>6</td>
<td>3</td>
<td>NaN</td>
<td>191</td>
<td>197</td>
<td>1</td>
<td>5</td>
<td>260</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">mean</td>
<td>224.276353</td>
<td>NaN</td>
<td>NaN</td>
<td>0.820809</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">std</td>
<td>132.302297</td>
<td>NaN</td>
<td>NaN</td>
<td>0.384067</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">min</td>
<td>1.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>0.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">25%</td>
<td>112.500000</td>
<td>NaN</td>
<td>NaN</td>
<td>1.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">50%</td>
<td>221.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>1.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">75%</td>
<td>346.500000</td>
<td>NaN</td>
<td>NaN</td>
<td>1.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">max</td>
<td>450.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>1.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Because the dataframe consits of authors and illustrators per book, the size of the dataframe is much larger than the listed graphic novels. Because we only want to see the authors of the book we update the dataframe by dropping rows that are of authors. We do this by checking similarities between author’s ‘ID’ and rel_book_author’s ‘AuthorID’ values, putting those values into a list, and then updating the contents of the dataframe by cross checking between the list and the dataframe’s ‘ID’ column.</p>
<div id="f30615d7" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>authorID <span class="op">=</span> []</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> rel_book_author[<span class="st">'AuthorID'</span>]:</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> i <span class="kw">in</span> authors[<span class="st">'ID'</span>].values:</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    authorID.append(i)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="89663a80" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>authors <span class="op">=</span> authors[authors[<span class="st">'ID'</span>].isin(authorID)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now that we have a dataframe consisting of only authors we can check for missing values and update if needed.</p>
<div id="a044489b" class="cell" data-scrolled="true" data-execution_count="18">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>authors[authors[<span class="st">'Gender_ID'</span>].isnull()]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="18">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">ID</th>
<th data-quarto-table-cell-role="th">FirstName</th>
<th data-quarto-table-cell-role="th">LastName</th>
<th data-quarto-table-cell-role="th">Gender_ID</th>
<th data-quarto-table-cell-role="th">CountryOfOriginID</th>
<th data-quarto-table-cell-role="th">CountryOfResidence</th>
<th data-quarto-table-cell-role="th">DateOfDeath</th>
<th data-quarto-table-cell-role="th">DateOfBirth</th>
<th data-quarto-table-cell-role="th">Ethnicity</th>
<th data-quarto-table-cell-role="th">PenName</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">233</td>
<td>298</td>
<td>A. B.</td>
<td>Sina</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>Unknown</td>
<td>NaN</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="7fe2875d" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>authors.loc[<span class="dv">233</span>, <span class="st">'Gender_ID'</span>] <span class="op">=</span> <span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="4f0d2107" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>authors[authors[<span class="st">'CountryOfOriginID'</span>].isnull()]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="20">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">ID</th>
<th data-quarto-table-cell-role="th">FirstName</th>
<th data-quarto-table-cell-role="th">LastName</th>
<th data-quarto-table-cell-role="th">Gender_ID</th>
<th data-quarto-table-cell-role="th">CountryOfOriginID</th>
<th data-quarto-table-cell-role="th">CountryOfResidence</th>
<th data-quarto-table-cell-role="th">DateOfDeath</th>
<th data-quarto-table-cell-role="th">DateOfBirth</th>
<th data-quarto-table-cell-role="th">Ethnicity</th>
<th data-quarto-table-cell-role="th">PenName</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">32</td>
<td>37</td>
<td>Brian</td>
<td>Fies</td>
<td>1.0</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>Unknown</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">72</td>
<td>88</td>
<td>Leela</td>
<td>Corman</td>
<td>0.0</td>
<td>NaN</td>
<td>USA</td>
<td>NaN</td>
<td>1976-01-01</td>
<td>Unknown</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">103</td>
<td>130</td>
<td>Sydney</td>
<td>Padua</td>
<td>0.0</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>White</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">188</td>
<td>235</td>
<td>Joshua W.</td>
<td>Cotter</td>
<td>1.0</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>White</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">212</td>
<td>265</td>
<td>Sarah</td>
<td>Leavitt</td>
<td>0.0</td>
<td>NaN</td>
<td>Canada</td>
<td>NaN</td>
<td>NaN</td>
<td>White</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">233</td>
<td>298</td>
<td>A. B.</td>
<td>Sina</td>
<td>1.0</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>Unknown</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">306</td>
<td>397</td>
<td>Karl</td>
<td>Rusnak</td>
<td>1.0</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">346</td>
<td>445</td>
<td>Martin I</td>
<td>Green</td>
<td>1.0</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="f3957df6" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>authors.loc[[<span class="dv">32</span>, <span class="dv">72</span>, <span class="dv">188</span>, <span class="dv">306</span>, <span class="dv">346</span>], <span class="st">'CountryOfOriginID'</span>] <span class="op">=</span> <span class="st">'USA'</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>authors.loc[[<span class="dv">103</span>, <span class="dv">212</span>], <span class="st">'CountryOfOriginID'</span>] <span class="op">=</span> <span class="st">'Canada'</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>authors.loc[<span class="dv">233</span>, <span class="st">'CountryOfOriginID'</span>] <span class="op">=</span> <span class="st">'Iran'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="4d0a5789" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>authors[authors[<span class="st">'Ethnicity'</span>].isnull()]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="22">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">ID</th>
<th data-quarto-table-cell-role="th">FirstName</th>
<th data-quarto-table-cell-role="th">LastName</th>
<th data-quarto-table-cell-role="th">Gender_ID</th>
<th data-quarto-table-cell-role="th">CountryOfOriginID</th>
<th data-quarto-table-cell-role="th">CountryOfResidence</th>
<th data-quarto-table-cell-role="th">DateOfDeath</th>
<th data-quarto-table-cell-role="th">DateOfBirth</th>
<th data-quarto-table-cell-role="th">Ethnicity</th>
<th data-quarto-table-cell-role="th">PenName</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">306</td>
<td>397</td>
<td>Karl</td>
<td>Rusnak</td>
<td>1.0</td>
<td>USA</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">346</td>
<td>445</td>
<td>Martin I</td>
<td>Green</td>
<td>1.0</td>
<td>USA</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="5b342414" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>authors.loc[[<span class="dv">306</span>, <span class="dv">346</span>], <span class="st">'Ethnicity'</span>] <span class="op">=</span> <span class="st">'White'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="graphic_novels-dataframe" class="level4">
<h4 class="anchored" data-anchor-id="graphic_novels-dataframe"><em>graphic_novels DataFrame</em></h4>
<div id="2f2c56cf" class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>graphic_novels.describe(include<span class="op">=</span><span class="st">'all'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="24">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">ID</th>
<th data-quarto-table-cell-role="th">Title</th>
<th data-quarto-table-cell-role="th">Mentions</th>
<th data-quarto-table-cell-role="th">Date Published</th>
<th data-quarto-table-cell-role="th">Image</th>
<th data-quarto-table-cell-role="th">Original Language</th>
<th data-quarto-table-cell-role="th">Foreign Key</th>
<th data-quarto-table-cell-role="th">GN_Source</th>
<th data-quarto-table-cell-role="th">color_type</th>
<th data-quarto-table-cell-role="th">Limited Series</th>
<th data-quarto-table-cell-role="th">Book Series</th>
<th data-quarto-table-cell-role="th">Unlimited Series</th>
<th data-quarto-table-cell-role="th">ISBN</th>
<th data-quarto-table-cell-role="th">Directory</th>
<th data-quarto-table-cell-role="th">Avg Rating</th>
<th data-quarto-table-cell-role="th">Number of Ratings</th>
<th data-quarto-table-cell-role="th">Original Title</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>252.000000</td>
<td>252</td>
<td>252.000000</td>
<td>252</td>
<td>250</td>
<td>252</td>
<td>252.000000</td>
<td>211</td>
<td>252</td>
<td>252.000000</td>
<td>252.000000</td>
<td>252.000000</td>
<td>252</td>
<td>200</td>
<td>252.000000</td>
<td>252.000000</td>
<td>236</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">unique</td>
<td>NaN</td>
<td>252</td>
<td>NaN</td>
<td>215</td>
<td>250</td>
<td>5</td>
<td>NaN</td>
<td>27</td>
<td>4</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>244</td>
<td>200</td>
<td>NaN</td>
<td>NaN</td>
<td>235</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">top</td>
<td>NaN</td>
<td>A Complete Lowlife</td>
<td>NaN</td>
<td>1/1/94</td>
<td>A Complete Lowlife.jpg</td>
<td>English</td>
<td>NaN</td>
<td>search.proquest.com</td>
<td>colour</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>9.7814E+12</td>
<td>Ode_to_Kirihito_Part_Two</td>
<td>NaN</td>
<td>NaN</td>
<td>Kirihito Sanka</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">freq</td>
<td>NaN</td>
<td>1</td>
<td>NaN</td>
<td>5</td>
<td>1</td>
<td>228</td>
<td>NaN</td>
<td>50</td>
<td>119</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>6</td>
<td>1</td>
<td>NaN</td>
<td>NaN</td>
<td>2</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">mean</td>
<td>157.123016</td>
<td>NaN</td>
<td>9.115079</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>0.452381</td>
<td>NaN</td>
<td>NaN</td>
<td>0.373016</td>
<td>0.166667</td>
<td>0.055556</td>
<td>NaN</td>
<td>NaN</td>
<td>3.924921</td>
<td>12409.357143</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">std</td>
<td>91.796527</td>
<td>NaN</td>
<td>26.350508</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>0.498718</td>
<td>NaN</td>
<td>NaN</td>
<td>0.484569</td>
<td>0.373420</td>
<td>0.229517</td>
<td>NaN</td>
<td>NaN</td>
<td>0.292950</td>
<td>36681.186674</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">min</td>
<td>1.000000</td>
<td>NaN</td>
<td>0.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>0.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>3.010000</td>
<td>4.000000</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">25%</td>
<td>78.750000</td>
<td>NaN</td>
<td>0.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>0.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>3.740000</td>
<td>723.000000</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">50%</td>
<td>162.500000</td>
<td>NaN</td>
<td>2.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>0.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>3.930000</td>
<td>1906.000000</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">75%</td>
<td>230.000000</td>
<td>NaN</td>
<td>7.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>1.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>1.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>4.140000</td>
<td>7458.250000</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">max</td>
<td>335.000000</td>
<td>NaN</td>
<td>294.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>1.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>4.550000</td>
<td>432336.000000</td>
<td>NaN</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Although there are some missing values, they are from columns that serve no purpose towards the question nor analysis.</p>
</section>
<section id="book_genres-dataframe" class="level4">
<h4 class="anchored" data-anchor-id="book_genres-dataframe">book_genres DataFrame</h4>
<div id="f67e5165" class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>book_genres.describe(include<span class="op">=</span><span class="st">'all'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="25">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">ID</th>
<th data-quarto-table-cell-role="th">BookID</th>
<th data-quarto-table-cell-role="th">SourceID</th>
<th data-quarto-table-cell-role="th">GenreID</th>
<th data-quarto-table-cell-role="th">isMain</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>333.000000</td>
<td>333.000000</td>
<td>331</td>
<td>333</td>
<td>333.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">unique</td>
<td>NaN</td>
<td>NaN</td>
<td>16</td>
<td>28</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">top</td>
<td>NaN</td>
<td>NaN</td>
<td>amazon.com</td>
<td>Literary Fiction</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">freq</td>
<td>NaN</td>
<td>NaN</td>
<td>185</td>
<td>47</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">mean</td>
<td>267.552553</td>
<td>165.942943</td>
<td>NaN</td>
<td>NaN</td>
<td>0.756757</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">std</td>
<td>133.991147</td>
<td>94.253470</td>
<td>NaN</td>
<td>NaN</td>
<td>0.429686</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">min</td>
<td>3.000000</td>
<td>1.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">25%</td>
<td>166.000000</td>
<td>84.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>1.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">50%</td>
<td>286.000000</td>
<td>170.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>1.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">75%</td>
<td>378.000000</td>
<td>246.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>1.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">max</td>
<td>479.000000</td>
<td>335.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>1.000000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Same as graphic_novels, nothing of importance needs to be filled.</p>
</section>
<section id="issue-dataframe" class="level4">
<h4 class="anchored" data-anchor-id="issue-dataframe"><em>issue DataFrame</em></h4>
<div id="607a58ec" class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>issue.describe(include<span class="op">=</span><span class="st">'all'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="26">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">ID</th>
<th data-quarto-table-cell-role="th">FormatID</th>
<th data-quarto-table-cell-role="th">Edition</th>
<th data-quarto-table-cell-role="th">BookID</th>
<th data-quarto-table-cell-role="th">LanguageID</th>
<th data-quarto-table-cell-role="th">Mentions</th>
<th data-quarto-table-cell-role="th">Pages</th>
<th data-quarto-table-cell-role="th">PlaceOfPublicationID</th>
<th data-quarto-table-cell-role="th">PublisherID</th>
<th data-quarto-table-cell-role="th">Date</th>
<th data-quarto-table-cell-role="th">Width</th>
<th data-quarto-table-cell-role="th">Depth</th>
<th data-quarto-table-cell-role="th">Height</th>
<th data-quarto-table-cell-role="th">Unit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>354.000000</td>
<td>354</td>
<td>183</td>
<td>354.000000</td>
<td>235</td>
<td>171.000000</td>
<td>348.000000</td>
<td>352</td>
<td>353</td>
<td>354</td>
<td>342.000000</td>
<td>342.000000</td>
<td>342.000000</td>
<td>338</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">unique</td>
<td>NaN</td>
<td>2</td>
<td>66</td>
<td>NaN</td>
<td>2</td>
<td>NaN</td>
<td>NaN</td>
<td>32</td>
<td>97</td>
<td>304</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>2</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">top</td>
<td>NaN</td>
<td>SC</td>
<td>First Edition</td>
<td>NaN</td>
<td>English</td>
<td>NaN</td>
<td>NaN</td>
<td>New York, USA</td>
<td>Drawn and Quarterly</td>
<td>2012-05-01</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>inches</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">freq</td>
<td>NaN</td>
<td>201</td>
<td>34</td>
<td>NaN</td>
<td>231</td>
<td>NaN</td>
<td>NaN</td>
<td>97</td>
<td>35</td>
<td>3</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>328</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">mean</td>
<td>242.745763</td>
<td>NaN</td>
<td>NaN</td>
<td>153.621469</td>
<td>NaN</td>
<td>1.578947</td>
<td>230.163793</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>7.590058</td>
<td>0.811404</td>
<td>10.238596</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">std</td>
<td>128.502831</td>
<td>NaN</td>
<td>NaN</td>
<td>91.130254</td>
<td>NaN</td>
<td>0.981248</td>
<td>140.246507</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>2.415411</td>
<td>0.441291</td>
<td>3.250432</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">min</td>
<td>23.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>0.000000</td>
<td>NaN</td>
<td>1.000000</td>
<td>66.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>4.200000</td>
<td>0.200000</td>
<td>5.500000</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">25%</td>
<td>129.750000</td>
<td>NaN</td>
<td>NaN</td>
<td>71.500000</td>
<td>NaN</td>
<td>1.000000</td>
<td>135.750000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>6.500000</td>
<td>0.500000</td>
<td>9.000000</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">50%</td>
<td>245.500000</td>
<td>NaN</td>
<td>NaN</td>
<td>155.500000</td>
<td>NaN</td>
<td>1.000000</td>
<td>200.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>6.900000</td>
<td>0.700000</td>
<td>9.950000</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">75%</td>
<td>349.750000</td>
<td>NaN</td>
<td>NaN</td>
<td>223.750000</td>
<td>NaN</td>
<td>2.000000</td>
<td>281.750000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>8.000000</td>
<td>1.000000</td>
<td>10.500000</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">max</td>
<td>477.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>335.000000</td>
<td>NaN</td>
<td>5.000000</td>
<td>1344.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>23.500000</td>
<td>2.600000</td>
<td>27.400000</td>
<td>NaN</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="645aa150" class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>issue[issue[<span class="st">'Pages'</span>].isnull()]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="27">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">ID</th>
<th data-quarto-table-cell-role="th">FormatID</th>
<th data-quarto-table-cell-role="th">Edition</th>
<th data-quarto-table-cell-role="th">BookID</th>
<th data-quarto-table-cell-role="th">LanguageID</th>
<th data-quarto-table-cell-role="th">Mentions</th>
<th data-quarto-table-cell-role="th">Pages</th>
<th data-quarto-table-cell-role="th">PlaceOfPublicationID</th>
<th data-quarto-table-cell-role="th">PublisherID</th>
<th data-quarto-table-cell-role="th">Date</th>
<th data-quarto-table-cell-role="th">Width</th>
<th data-quarto-table-cell-role="th">Depth</th>
<th data-quarto-table-cell-role="th">Height</th>
<th data-quarto-table-cell-role="th">Unit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">136</td>
<td>192</td>
<td>SC</td>
<td>NaN</td>
<td>119</td>
<td>English</td>
<td>2.0</td>
<td>NaN</td>
<td>London, UK</td>
<td>Hodder Childrens Books</td>
<td>2014-01-01</td>
<td>6.7</td>
<td>0.5</td>
<td>9.1</td>
<td>inches</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">178</td>
<td>247</td>
<td>HC</td>
<td>NaN</td>
<td>162</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>Montreal, Canada</td>
<td>Black Eye Books</td>
<td>1997-01-01</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">200</td>
<td>276</td>
<td>SC</td>
<td>First Edition</td>
<td>178</td>
<td>English</td>
<td>NaN</td>
<td>NaN</td>
<td>Toronto, Canada</td>
<td>Vortex Comics Inc.</td>
<td>1992-01-01</td>
<td>6.1</td>
<td>0.5</td>
<td>8.9</td>
<td>inches</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">285</td>
<td>374</td>
<td>SC</td>
<td>NaN</td>
<td>255</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>2013-01-01</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">296</td>
<td>385</td>
<td>HC</td>
<td>NaN</td>
<td>260</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>El Capitan Books</td>
<td>2001-01-01</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">318</td>
<td>425</td>
<td>HC</td>
<td>Signed limited edition</td>
<td>291</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>Townshend, USA</td>
<td>King Hell Press</td>
<td>1992-01-01</td>
<td>6.6</td>
<td>1.1</td>
<td>9.1</td>
<td>inches</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="3567588b" class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>issue[issue[<span class="st">'PlaceOfPublicationID'</span>].isnull()]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="28">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">ID</th>
<th data-quarto-table-cell-role="th">FormatID</th>
<th data-quarto-table-cell-role="th">Edition</th>
<th data-quarto-table-cell-role="th">BookID</th>
<th data-quarto-table-cell-role="th">LanguageID</th>
<th data-quarto-table-cell-role="th">Mentions</th>
<th data-quarto-table-cell-role="th">Pages</th>
<th data-quarto-table-cell-role="th">PlaceOfPublicationID</th>
<th data-quarto-table-cell-role="th">PublisherID</th>
<th data-quarto-table-cell-role="th">Date</th>
<th data-quarto-table-cell-role="th">Width</th>
<th data-quarto-table-cell-role="th">Depth</th>
<th data-quarto-table-cell-role="th">Height</th>
<th data-quarto-table-cell-role="th">Unit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">285</td>
<td>374</td>
<td>SC</td>
<td>NaN</td>
<td>255</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>2013-01-01</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">296</td>
<td>385</td>
<td>HC</td>
<td>NaN</td>
<td>260</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>El Capitan Books</td>
<td>2001-01-01</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="a813cd67" class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>issue[issue[<span class="st">'PublisherID'</span>].isnull()]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="29">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">ID</th>
<th data-quarto-table-cell-role="th">FormatID</th>
<th data-quarto-table-cell-role="th">Edition</th>
<th data-quarto-table-cell-role="th">BookID</th>
<th data-quarto-table-cell-role="th">LanguageID</th>
<th data-quarto-table-cell-role="th">Mentions</th>
<th data-quarto-table-cell-role="th">Pages</th>
<th data-quarto-table-cell-role="th">PlaceOfPublicationID</th>
<th data-quarto-table-cell-role="th">PublisherID</th>
<th data-quarto-table-cell-role="th">Date</th>
<th data-quarto-table-cell-role="th">Width</th>
<th data-quarto-table-cell-role="th">Depth</th>
<th data-quarto-table-cell-role="th">Height</th>
<th data-quarto-table-cell-role="th">Unit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">285</td>
<td>374</td>
<td>SC</td>
<td>NaN</td>
<td>255</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>2013-01-01</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="0f5416fe" class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>issue.loc[<span class="dv">136</span>, <span class="st">'Pages'</span>] <span class="op">=</span> <span class="dv">128</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>issue.loc[<span class="dv">178</span>, <span class="st">'Pages'</span>] <span class="op">=</span> <span class="dv">152</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>issue.loc[<span class="dv">200</span>, <span class="st">'Pages'</span>] <span class="op">=</span> <span class="dv">240</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>issue.loc[<span class="dv">285</span>, [<span class="st">'Pages'</span>, <span class="st">'PlaceOfPublicationID'</span>, <span class="st">'PublisherID'</span>]] <span class="op">=</span> [<span class="dv">240</span>, <span class="st">'New York, USA'</span>, <span class="st">'Bantam Books'</span>]</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>issue.loc[<span class="dv">296</span>, [<span class="st">'Pages'</span>, <span class="st">'PlaceOfPublicationID'</span>]] <span class="op">=</span> [<span class="dv">224</span>, <span class="st">'Cincinnati, USA'</span>]</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>issue.loc[<span class="dv">318</span>, <span class="st">'Pages'</span>] <span class="op">=</span> <span class="dv">176</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="c.-looking-for-duplicated-rows" class="level3">
<h3 class="anchored" data-anchor-id="c.-looking-for-duplicated-rows">c.&nbsp;Looking for Duplicated Rows</h3>
<p>We don’t include the ‘ID’ column from the datasets because as mentioned in ‘About the Data’ the ’ID’s were created from a cheap source.</p>
<div id="35be490b" class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(adaptations.duplicated(subset<span class="op">=</span>[<span class="st">'BookID'</span>, <span class="st">'Type'</span>, <span class="st">'Title'</span>, <span class="st">'Publication'</span>]).<span class="bu">sum</span>())</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(authors.duplicated(subset<span class="op">=</span>[<span class="st">'FirstName'</span>, <span class="st">'LastName'</span>, <span class="st">'Gender_ID'</span>, <span class="st">'CountryOfOriginID'</span>, <span class="st">'CountryOfResidence'</span>, <span class="st">'DateOfDeath'</span>, <span class="st">'DateOfBirth'</span>, <span class="st">'Ethnicity'</span>, <span class="st">'PenName'</span>]).<span class="bu">sum</span>())</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(graphic_novels.duplicated(subset<span class="op">=</span>[<span class="st">'Title'</span>, <span class="st">'Mentions'</span>, <span class="st">'Date Published'</span>, <span class="st">'Image'</span>, <span class="st">'Original Language'</span>, <span class="st">'Foreign Key'</span>,<span class="st">'GN_Source'</span>, <span class="st">'color_type'</span>, <span class="st">'Limited Series'</span>, <span class="st">'Book Series'</span>, <span class="st">'Unlimited Series'</span>, <span class="st">'ISBN'</span>, <span class="st">'Directory'</span>,<span class="st">'Avg Rating'</span>, <span class="st">'Number of Ratings'</span>, <span class="st">'Original Title'</span>]).<span class="bu">sum</span>())</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(book_genres.duplicated(subset<span class="op">=</span>[<span class="st">'BookID'</span>, <span class="st">'SourceID'</span>, <span class="st">'GenreID'</span>, <span class="st">'isMain'</span>]).<span class="bu">sum</span>())</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(issue.duplicated(subset<span class="op">=</span>[<span class="st">'FormatID'</span>, <span class="st">'Edition'</span>, <span class="st">'BookID'</span>, <span class="st">'LanguageID'</span>, <span class="st">'Mentions'</span>, <span class="st">'Pages'</span>, <span class="st">'PlaceOfPublicationID'</span>, <span class="st">'PublisherID'</span>, <span class="st">'Date'</span>, <span class="st">'Width'</span>, <span class="st">'Depth'</span>, <span class="st">'Height'</span>, <span class="st">'Unit'</span>]).<span class="bu">sum</span>())</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(rel_book_author.duplicated(subset<span class="op">=</span>[<span class="st">'BookID'</span>, <span class="st">'AuthorID'</span>]).<span class="bu">sum</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0
0
0
0
0
8</code></pre>
</div>
</div>
<p>There are 8 duplicated rows in the rel_book_author dataframe so we drop them:</p>
<div id="93dc3236" class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>rel_book_author.drop_duplicates(subset<span class="op">=</span>[<span class="st">'BookID'</span>, <span class="st">'AuthorID'</span>], inplace<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>While there are no exact duplicates, we look for duplicates in ‘BookID’ since some of the dataframes listed sizes greater than the amount of listed graphic novels.</p>
<div id="a7045058" class="cell" data-execution_count="33">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(adaptations.duplicated(<span class="st">'BookID'</span>).<span class="bu">sum</span>())</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(authors.duplicated(subset<span class="op">=</span>[<span class="st">'FirstName'</span>, <span class="st">'LastName'</span>]).<span class="bu">sum</span>())</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(graphic_novels.duplicated([<span class="st">'ID'</span>, <span class="st">'Title'</span>]).<span class="bu">sum</span>())</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(book_genres.duplicated(<span class="st">'BookID'</span>).<span class="bu">sum</span>())</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(issue.duplicated(<span class="st">'BookID'</span>).<span class="bu">sum</span>())</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(rel_book_author.duplicated(<span class="st">'BookID'</span>).<span class="bu">sum</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>28
0
0
81
101
27</code></pre>
</div>
</div>
<p>The above results make sense as there should only be one of each author and graphic novel title from those specific dataframes. The other tables will overlap as they list every occurence where a single book has had an adaptation, genre, issue, and author. It is not uncommon for a book to have multiple adaptations, genres, issues, and authors.</p>
<p>In addition, this calculation show that out of the 252 titles in graphic_novels listed, there is a total of 39 single pieces of work that have been adapted at least once, which is <strong>15.5% of total graphic novels published from the mid-70s to 2017.</strong></p>
<p>While not addressing our questions, this provides further evidence for the lack of adaptations of graphic novels.</p>
<div id="015054d7" class="cell" data-execution_count="34">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>book_adaptation <span class="op">=</span> adaptations.shape[<span class="dv">0</span>] <span class="op">-</span> adaptations.duplicated(<span class="st">'BookID'</span>).<span class="bu">sum</span>()</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(book_adaptation)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>percentage_adaptations <span class="op">=</span> (book_adaptation<span class="op">/</span>graphic_novels.shape[<span class="dv">0</span>]) <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(percentage_adaptations)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>39
15.476190476190476</code></pre>
</div>
</div>
</section>
<section id="d.-changing-the-date" class="level3">
<h3 class="anchored" data-anchor-id="d.-changing-the-date">d.&nbsp;Changing the Date</h3>
<p>Some tables included dates, such as publication dates, written in a string format. Since it could be useful to see whether the year of publication has an effect on our questions, we change the dates into numerical form.</p>
<div id="040369de" class="cell" data-execution_count="35">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>adaptations[<span class="st">'Publication'</span>] <span class="op">=</span> pd.to_datetime(adaptations[<span class="st">'Publication'</span>])</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>adaptations[<span class="st">'Year'</span>] <span class="op">=</span> adaptations[<span class="st">'Publication'</span>].dt.year</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>adaptations[<span class="st">'Month'</span>] <span class="op">=</span> adaptations[<span class="st">'Publication'</span>].dt.month</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>adaptations[<span class="st">'Day'</span>] <span class="op">=</span> adaptations[<span class="st">'Publication'</span>].dt.day</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>graphic_novels[<span class="st">'Date Published'</span>] <span class="op">=</span> pd.to_datetime(graphic_novels[<span class="st">'Date Published'</span>], <span class="bu">format</span><span class="op">=</span><span class="st">'%m/</span><span class="sc">%d</span><span class="st">/%y'</span>)</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>graphic_novels[<span class="st">'Year'</span>] <span class="op">=</span> graphic_novels[<span class="st">'Date Published'</span>].dt.year</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>graphic_novels[<span class="st">'Month'</span>] <span class="op">=</span> graphic_novels[<span class="st">'Date Published'</span>].dt.month</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>graphic_novels[<span class="st">'Day'</span>] <span class="op">=</span> graphic_novels[<span class="st">'Date Published'</span>].dt.day</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="exploring-the-data-with-visualizations" class="level2">
<h2 class="anchored" data-anchor-id="exploring-the-data-with-visualizations">3. Exploring the Data with Visualizations</h2>
<p>Now that the data is fairly clean we can use it to visually explore trends of the data.</p>
<section id="a.-adaptations-dataframe" class="level3">
<h3 class="anchored" data-anchor-id="a.-adaptations-dataframe">a. Adaptations DataFrame</h3>
<section id="bookid" class="level4">
<h4 class="anchored" data-anchor-id="bookid"><em>BookID</em></h4>
<div id="dc7becb7" class="cell" data-execution_count="36">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>adaptations[<span class="st">'BookID'</span>].value_counts().plot(kind<span class="op">=</span><span class="st">'bar'</span>, color<span class="op">=</span><span class="st">'brown'</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="GraphicNovels_files/figure-html/cell-37-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>There is a total of 9 out of 39 adapted books that have been adapted more than once, with the book with the ID ‘78’ has being adapted the most.</p>
</section>
<section id="type" class="level4">
<h4 class="anchored" data-anchor-id="type"><em>Type</em></h4>
<div id="40b8ea51" class="cell" data-execution_count="37">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>adaptations[<span class="st">'Type'</span>].value_counts().plot(kind<span class="op">=</span><span class="st">'bar'</span>, color<span class="op">=</span><span class="st">'brown'</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="GraphicNovels_files/figure-html/cell-38-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Films are the most popular type of adaptation, however,‘Type’ is made up of randomly inputted string, with no specific code for what type of adaptation they are.</p>
</section>
<section id="year" class="level4">
<h4 class="anchored" data-anchor-id="year"><em>Year</em></h4>
<div id="6c256ca2" class="cell" data-execution_count="38">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>adaptations[<span class="st">'Year'</span>].value_counts().plot(kind<span class="op">=</span><span class="st">'bar'</span>, color<span class="op">=</span><span class="st">'brown'</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="GraphicNovels_files/figure-html/cell-39-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Most of adaptations were published in the 2000s, specifically between 2005-2013. Adaptations began releasing in the early 1970s.</p>
</section>
</section>
<section id="b.-authors-dataframe" class="level3">
<h3 class="anchored" data-anchor-id="b.-authors-dataframe">b. authors DataFrame</h3>
<section id="genderid" class="level4">
<h4 class="anchored" data-anchor-id="genderid"><em>GenderID</em></h4>
<div id="07b8e79e" class="cell" data-execution_count="39">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>authors[<span class="st">'Gender_ID'</span>].value_counts().plot(x <span class="op">=</span> <span class="st">'Gender'</span>, y <span class="op">=</span> <span class="st">'Count'</span>, kind<span class="op">=</span><span class="st">'pie'</span>, colors<span class="op">=</span>[<span class="st">'green'</span>, <span class="st">'lightgreen'</span>], figsize<span class="op">=</span>(<span class="dv">5</span>, <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="GraphicNovels_files/figure-html/cell-40-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Majority of Male authors dominate graphic novels.</p>
</section>
<section id="countryoforiginid" class="level4">
<h4 class="anchored" data-anchor-id="countryoforiginid"><em>CountryOfOriginID</em></h4>
<div id="9cacdcc2" class="cell" data-execution_count="40">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>authors[<span class="st">'CountryOfOriginID'</span>].value_counts().plot(kind<span class="op">=</span><span class="st">'bar'</span>, color<span class="op">=</span><span class="st">'green'</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">2</span>), rot<span class="op">=</span><span class="dv">75</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="GraphicNovels_files/figure-html/cell-41-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Majority of authors come from the USA and English speaking countries.</p>
</section>
<section id="ethnicity" class="level4">
<h4 class="anchored" data-anchor-id="ethnicity"><em>Ethnicity</em></h4>
<div id="9b8774e7" class="cell" data-execution_count="41">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>authors[<span class="st">'Ethnicity'</span>].value_counts().plot(kind<span class="op">=</span><span class="st">'bar'</span>, color<span class="op">=</span><span class="st">'green'</span>, figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="dv">2</span>), rot<span class="op">=</span><span class="dv">45</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="GraphicNovels_files/figure-html/cell-42-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Majority of authors are of White race, followed by Asian and Unknown.</p>
</section>
</section>
<section id="c.-graphic_novels-dataframe" class="level3">
<h3 class="anchored" data-anchor-id="c.-graphic_novels-dataframe">c.&nbsp;graphic_novels DataFrame</h3>
<section id="year-1" class="level4">
<h4 class="anchored" data-anchor-id="year-1"><em>Year</em></h4>
<div id="7e1c4534" class="cell" data-execution_count="42">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>graphic_novels[<span class="st">'Year'</span>].value_counts().plot(kind<span class="op">=</span><span class="st">'bar'</span>, color<span class="op">=</span><span class="st">'pink'</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="GraphicNovels_files/figure-html/cell-43-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Majority of graphic novels were published in the 2000s. There is an upward trend in publication of graphic novels as the years go by. The most popular year to publish was 2015.</p>
</section>
<section id="originial-language" class="level4">
<h4 class="anchored" data-anchor-id="originial-language"><em>Originial Language</em></h4>
<div id="74720de3" class="cell" data-execution_count="43">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>graphic_novels[<span class="st">'Original Language'</span>].value_counts().plot(kind<span class="op">=</span><span class="st">'bar'</span>, color<span class="op">=</span><span class="st">'pink'</span>, figsize<span class="op">=</span>(<span class="dv">5</span>, <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="GraphicNovels_files/figure-html/cell-44-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>English is the most common language for graphic novels.</p>
</section>
<section id="avg-rating" class="level4">
<h4 class="anchored" data-anchor-id="avg-rating"><em>Avg Rating</em></h4>
<div id="1f6f574e" class="cell" data-execution_count="44">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>graphic_novels[<span class="st">'Avg Rating'</span>].plot.hist(bins <span class="op">=</span> <span class="dv">150</span>, color<span class="op">=</span><span class="st">'pink'</span>, figsize<span class="op">=</span>(<span class="dv">20</span>, <span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="GraphicNovels_files/figure-html/cell-45-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Average ratings are skewed to the right with the peak being at 3.8, and slowly decends towards 5.</p>
</section>
<section id="number-of-ratings" class="level4">
<h4 class="anchored" data-anchor-id="number-of-ratings"><em>Number of Ratings</em></h4>
<div id="41334779" class="cell" data-execution_count="45">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>graphic_novels[<span class="dv">0</span>:<span class="dv">50</span>].plot.bar(x <span class="op">=</span> <span class="st">'Title'</span>, y <span class="op">=</span> <span class="st">'Number of Ratings'</span>, color<span class="op">=</span><span class="st">'pink'</span>, figsize<span class="op">=</span>(<span class="dv">20</span>, <span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="GraphicNovels_files/figure-html/cell-46-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Too many graphic novels to plot, however it shows number of ratings of some of the more popular and least popular books based on how many people rated the book.</p>
</section>
<section id="avg-rating-vs-number-of-ratings" class="level4">
<h4 class="anchored" data-anchor-id="avg-rating-vs-number-of-ratings"><em>Avg Rating vs Number of Ratings</em></h4>
<div id="1a533a23" class="cell" data-execution_count="46">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>graphic_novels.plot.scatter(x <span class="op">=</span> <span class="st">'Avg Rating'</span>, y <span class="op">=</span> <span class="st">'Number of Ratings'</span>, color<span class="op">=</span><span class="st">'pink'</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">3</span>), marker <span class="op">=</span> <span class="st">'o'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="GraphicNovels_files/figure-html/cell-47-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Average book rating is around the 3.6-4.2 range. There is also a small correlation between number of ratings and average rating in that the more number of ratings, the higher average rating a book receives.</p>
</section>
<section id="limited-series-book-series-unlimited-series" class="level4">
<h4 class="anchored" data-anchor-id="limited-series-book-series-unlimited-series"><em>Limited Series, Book Series, Unlimited Series</em></h4>
<div id="27a45a9b" class="cell" data-execution_count="47">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>lim_counts <span class="op">=</span> graphic_novels[<span class="st">'Limited Series'</span>].value_counts()</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>book_counts <span class="op">=</span> graphic_novels[<span class="st">'Book Series'</span>].value_counts()</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>unlim_counts <span class="op">=</span> graphic_novels[<span class="st">'Unlimited Series'</span>].value_counts()</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>counts_df <span class="op">=</span> pd.DataFrame({<span class="st">'Limited Series'</span>: lim_counts,<span class="st">'Book Series'</span>: book_counts,<span class="st">'Unlimited Series'</span>: unlim_counts})</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>counts_df.plot.bar(color <span class="op">=</span> [<span class="st">'pink'</span>, <span class="st">'salmon'</span>, <span class="st">'lightsalmon'</span>], figsize <span class="op">=</span> (<span class="dv">5</span>,<span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="GraphicNovels_files/figure-html/cell-48-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>While majority of books are not limited, book, or unlimited series, those that were, were mostly Limited Series, follwed by being a part of a Book Series, and lastly an Unlimited Series.</p>
</section>
</section>
<section id="d.-book_genres-dataframe" class="level3">
<h3 class="anchored" data-anchor-id="d.-book_genres-dataframe">d.&nbsp;book_genres DataFrame</h3>
<section id="bookid-1" class="level4">
<h4 class="anchored" data-anchor-id="bookid-1"><em>BookID</em></h4>
<div id="f015a5d6" class="cell" data-execution_count="48">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>num_genres <span class="op">=</span> book_genres[<span class="st">'BookID'</span>].value_counts().reset_index()</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>num_genres.columns <span class="op">=</span> [<span class="st">'BookID'</span>, <span class="st">'Number of Genres per Book'</span>]</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>num_genres[<span class="st">'Number of Genres per Book'</span>].value_counts().plot.pie(colors <span class="op">=</span> [<span class="st">'orange'</span>, <span class="st">'darkorange'</span>, <span class="st">'orangered'</span>], figsize<span class="op">=</span>(<span class="dv">5</span>, <span class="dv">2</span>), title<span class="op">=</span><span class="st">'Number of Genres per Book'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="GraphicNovels_files/figure-html/cell-49-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Most books are listed with one genre, however, some have 2 or 3 genres listed per book.</p>
</section>
<section id="genreid" class="level4">
<h4 class="anchored" data-anchor-id="genreid"><em>GenreID</em></h4>
<div id="31a78970" class="cell" data-execution_count="49">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>book_genres[<span class="st">'GenreID'</span>].value_counts().plot(kind<span class="op">=</span><span class="st">'bar'</span>, rot<span class="op">=</span><span class="dv">60</span>, color<span class="op">=</span><span class="st">'orange'</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="GraphicNovels_files/figure-html/cell-50-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Literary fiction, Memoir, Fantasy, Superhero, and Coming of Age are the most popular genres for graphic novels.</p>
</section>
</section>
<section id="e.-issue-dataframe" class="level3">
<h3 class="anchored" data-anchor-id="e.-issue-dataframe">e. issue DataFrame</h3>
<section id="formatid" class="level4">
<h4 class="anchored" data-anchor-id="formatid"><em>FormatID</em></h4>
<div id="13c651d8" class="cell" data-execution_count="50">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>issue[<span class="st">'FormatID'</span>].value_counts().plot(kind<span class="op">=</span><span class="st">'pie'</span>, colors<span class="op">=</span> [<span class="st">'orchid'</span>, <span class="st">'purple'</span>], figsize<span class="op">=</span>(<span class="dv">3</span>,<span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="GraphicNovels_files/figure-html/cell-51-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Most books get published as Soft Covers, but there is a good handful of books getting published as Hard Cover. However, it is important to note that this aligns with the number of issues a book gets, so some books have been published as a soft cover and a hard cover.</p>
</section>
<section id="bookid-2" class="level4">
<h4 class="anchored" data-anchor-id="bookid-2"><em>BookID</em></h4>
<div id="b881dbb6" class="cell" data-execution_count="51">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>num_issues <span class="op">=</span> issue[<span class="st">'BookID'</span>].value_counts().reset_index()</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>num_issues.columns <span class="op">=</span> [<span class="st">'BookID'</span>, <span class="st">'Number of Issues per Book'</span>]</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>num_issues[<span class="st">'Number of Issues per Book'</span>].value_counts().plot.pie(colors <span class="op">=</span> [<span class="st">'orchid'</span>, <span class="st">'purple'</span>, <span class="st">'violet'</span>], figsize<span class="op">=</span>(<span class="dv">3</span>,<span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="GraphicNovels_files/figure-html/cell-52-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Most books have a single edition. About half have 2 editions released, and very few have 3 editions.</p>
</section>
<section id="pages" class="level4">
<h4 class="anchored" data-anchor-id="pages"><em>Pages</em></h4>
<div id="63a803c3" class="cell" data-execution_count="52">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>issue[<span class="st">'Pages'</span>].plot.hist(bins <span class="op">=</span> <span class="dv">100</span>, color<span class="op">=</span><span class="st">'orchid'</span>, figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="dv">3</span>), xlabel<span class="op">=</span><span class="st">'Pages'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="GraphicNovels_files/figure-html/cell-53-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Graph is skewed to the left, with most books having pages less than 200. There is an outlier that has more than 1200 pages.</p>
</section>
</section>
<section id="f.-rel_book_authors-dataframe" class="level3">
<h3 class="anchored" data-anchor-id="f.-rel_book_authors-dataframe">f.&nbsp;rel_book_authors DataFrame</h3>
<section id="bookid-3" class="level4">
<h4 class="anchored" data-anchor-id="bookid-3"><em>BookID</em></h4>
<div id="ca7506e9" class="cell" data-execution_count="53">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>num_authors <span class="op">=</span> rel_book_author[<span class="st">'BookID'</span>].value_counts().reset_index()</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>num_authors.columns <span class="op">=</span> [<span class="st">'BookID'</span>, <span class="st">'Number of Authors per Book'</span>]</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>num_authors[<span class="st">'Number of Authors per Book'</span>].value_counts().plot.bar(color <span class="op">=</span> <span class="st">'red'</span>, figsize<span class="op">=</span>(<span class="dv">5</span>, <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="GraphicNovels_files/figure-html/cell-54-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Majority of books have one author. Very few have 2, and almost zero have 3 and 4.</p>
</section>
<section id="authorid" class="level4">
<h4 class="anchored" data-anchor-id="authorid"><em>AuthorID</em></h4>
<div id="e4543888" class="cell" data-execution_count="54">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>num_authors <span class="op">=</span> rel_book_author[<span class="st">'AuthorID'</span>].value_counts().reset_index()</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>num_authors.columns <span class="op">=</span> [<span class="st">'BookID'</span>, <span class="st">'Number of Books per Author'</span>]</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>num_authors[<span class="st">'Number of Books per Author'</span>].value_counts().plot.bar(color <span class="op">=</span> <span class="st">'red'</span>, figsize<span class="op">=</span>(<span class="dv">5</span>, <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="GraphicNovels_files/figure-html/cell-55-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Most authors have published 1 graphic novel. A good handful has published 2 books. There are a couple of individuals that have participated in 6-10 novels.</p>
</section>
</section>
</section>
<section id="narrowing-the-scope" class="level2">
<h2 class="anchored" data-anchor-id="narrowing-the-scope">4. Narrowing the Scope</h2>
<p>Our ultimate goal is to answer the question: “What is the recipe for scoring an adaptation as a graphic novel?</p>
<p>We can begin by asking the question: “What are the traits in books that receive adaptations?”</p>
<p>To do so, we first must identify what <em>kind</em> of traits we want to examine…We look at the exploratory data to determine what factors (or columns) seemed to show the most variabilitly. - graphic_novels’s Year, the published year of books - graphic_novels’s Avg Rating, average ratings out of 5 stars of books on goodreads - graphic_novels’s Number of Ratings, amount of entires of ratings on goodreads - book_genres’s Genre, different genres of books - issues’s Pages, amount of pages per book</p>
<p>**Columns that had a dominant value were not included, as it is likely to be the same for all books.*</p>
<p>We must also identify the different groups we will be comparing.</p>
<p>Since we are testing adapted books, we will have to create a dataframe consisting of all books that have been adapted and compare that between all books and books that have not been adapted. It would also be interesting to test the difference between books that have been adapted more than once, books that have been adapted into a film, television series, and other.</p>
<p>In total, we have the following groups: - adapted books - books - non-adapted books - multiple adapted books - film adapted books - television adapted books - other adapted books</p>
<section id="a.-creating-the-group-dataframes" class="level3">
<h3 class="anchored" data-anchor-id="a.-creating-the-group-dataframes">a. Creating the Group DataFrames</h3>
<p>We create the seven groups of dataframes as it will be easier and faster to run analyses on. They each will contain their ‘BookID’ and ‘Title’.</p>
<section id="adaptations---made-up-of-all-books-that-have-been-adapted." class="level4">
<h4 class="anchored" data-anchor-id="adaptations---made-up-of-all-books-that-have-been-adapted."><em>Adaptations</em> - made up of all books that have been adapted.</h4>
<div id="4f773101" class="cell" data-execution_count="55">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>adap_books <span class="op">=</span> adaptations[[<span class="st">'BookID'</span>]].drop_duplicates().reset_index(drop<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="3c525718" class="cell" data-execution_count="56">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>adap_books_title <span class="op">=</span> []</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> index, i <span class="kw">in</span> adap_books.iterrows():</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> index, book <span class="kw">in</span> graphic_novels.iterrows():</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> i[<span class="st">'BookID'</span>] <span class="op">==</span> book[<span class="st">'ID'</span>]:</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>      adap_books_title.append(book[<span class="st">'Title'</span>])</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>adap_books[<span class="st">'Title'</span>] <span class="op">=</span> adap_books_title</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="books---made-up-of-all-books." class="level4">
<h4 class="anchored" data-anchor-id="books---made-up-of-all-books."><em>Books</em> - made up of all books.</h4>
<div id="7b3c330c" class="cell" data-execution_count="57">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>books <span class="op">=</span> graphic_novels[[<span class="st">'ID'</span>, <span class="st">'Title'</span>]]</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>books.columns <span class="op">=</span> [<span class="st">'BookID'</span>, <span class="st">'Title'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="non-adapted-books---made-up-of-all-books-that-have-not-been-adapated." class="level4">
<h4 class="anchored" data-anchor-id="non-adapted-books---made-up-of-all-books-that-have-not-been-adapated."><em>Non-Adapted Books</em> - made up of all books that have not been adapated.</h4>
<div id="866c0450" class="cell" data-execution_count="58">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>no_adap_books <span class="op">=</span> books[<span class="op">~</span>books[<span class="st">'BookID'</span>].isin(adaptations[<span class="st">'BookID'</span>])].reset_index(drop<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="multiple-adapted-books---made-up-of-books-that-have-been-adapated-more-than-once." class="level4">
<h4 class="anchored" data-anchor-id="multiple-adapted-books---made-up-of-books-that-have-been-adapated-more-than-once."><em>Multiple-Adapted Books</em> - made up of books that have been adapated more than once.</h4>
<div id="9a71af68" class="cell" data-execution_count="59">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>frequency_adaptations <span class="op">=</span> adaptations[<span class="st">'BookID'</span>].value_counts()</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>frequency_adaptations <span class="op">=</span> frequency_adaptations.reset_index()</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>frequency_adaptations.columns <span class="op">=</span> [<span class="st">'BookID'</span>, <span class="st">'Count'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="62e28b4d" class="cell" data-execution_count="60">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>mult_adap_id <span class="op">=</span> []</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> index, book <span class="kw">in</span> frequency_adaptations.iterrows():</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> book[<span class="st">'Count'</span>] <span class="op">&gt;</span> <span class="dv">1</span>: </span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>    mult_adap_id.append(book[<span class="st">'BookID'</span>])</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>mult_adap_name <span class="op">=</span> []</span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> mult_adap_id:</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> index, book <span class="kw">in</span> graphic_novels.iterrows():</span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> book[<span class="st">'ID'</span>] <span class="op">==</span> i:</span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>      mult_adap_name.append(book[<span class="st">'Title'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="489e5c21" class="cell" data-execution_count="61">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>mult_adap <span class="op">=</span> pd.DataFrame({<span class="st">'BookID'</span>: mult_adap_id, <span class="st">'Title'</span>: mult_adap_name})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="film-adapted-books---made-up-of-books-that-have-been-adapated-into-films." class="level4">
<h4 class="anchored" data-anchor-id="film-adapted-books---made-up-of-books-that-have-been-adapated-into-films."><em>Film Adapted Books</em> - made up of books that have been adapated into films.</h4>
<p><strong>Side Quest: Create Adaptation ‘Type’ columns</strong></p>
<p>However, before we can made the Film Adapted Books dataframe, or any dataframe that concerns the adaptations’ type, we need a better code that flags what kind of adaptation they are. As we saw from the data visualizations in adaptation, the type was input as a random string.</p>
<p>We can flag the strings by searching for associated words and grouping them together:</p>
<div id="d230334d" class="cell" data-execution_count="62">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>conditions <span class="op">=</span> [adaptations[<span class="st">'Type'</span>].<span class="bu">str</span>.contains(<span class="st">'(?:Film|Movie|Feature)'</span>, case<span class="op">=</span><span class="va">False</span>, regex<span class="op">=</span><span class="va">True</span>),</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>              adaptations[<span class="st">'Type'</span>].<span class="bu">str</span>.contains(<span class="st">'(?:Television|Series|Mini)'</span>, case<span class="op">=</span><span class="va">False</span>, regex<span class="op">=</span><span class="va">True</span>)]</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>choices <span class="op">=</span> [<span class="dv">1</span>, <span class="dv">2</span>]</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>adaptations[<span class="st">'TypeCode'</span>] <span class="op">=</span> np.select(conditions, choices, default<span class="op">=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we can continue with creating the film adapted dataframe:</p>
<div id="94d7221d" class="cell" data-execution_count="63">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>film_adap_id <span class="op">=</span> adaptations.loc[adaptations[<span class="st">'TypeCode'</span>] <span class="op">==</span> <span class="dv">1</span>, <span class="st">'BookID'</span>].tolist()</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>film_adap_name <span class="op">=</span> []</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> film_adap_id:</span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> index, book <span class="kw">in</span> books.iterrows():</span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> book[<span class="st">'BookID'</span>] <span class="op">==</span> i:</span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a>          film_adap_name.append(book[<span class="st">'Title'</span>])</span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a>film_adap <span class="op">=</span> pd.DataFrame({<span class="st">'BookID'</span>: film_adap_id, <span class="st">'Title'</span>: film_adap_name})</span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a>film_adap <span class="op">=</span> film_adap.drop_duplicates().reset_index(drop<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="television-adapted-dataframe---made-up-of-books-that-have-been-adapted-as-a-television-series-or-miniseries." class="level4">
<h4 class="anchored" data-anchor-id="television-adapted-dataframe---made-up-of-books-that-have-been-adapted-as-a-television-series-or-miniseries."><em>Television Adapted DataFrame</em> - made up of books that have been adapted as a television series or miniseries.</h4>
<div id="7ed9ff44" class="cell" data-execution_count="64">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>tel_adap_id <span class="op">=</span> adaptations.loc[adaptations[<span class="st">'TypeCode'</span>] <span class="op">==</span> <span class="dv">2</span>, <span class="st">'BookID'</span>].tolist()</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>tel_adap_name <span class="op">=</span> []</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> tel_adap_id:</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> index, book <span class="kw">in</span> books.iterrows():</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> book[<span class="st">'BookID'</span>] <span class="op">==</span> i:</span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>          tel_adap_name.append(book[<span class="st">'Title'</span>])</span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>tel_adap <span class="op">=</span> pd.DataFrame({<span class="st">'BookID'</span>: tel_adap_id, <span class="st">'Title'</span>: tel_adap_name})</span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a>tel_adap <span class="op">=</span> tel_adap.drop_duplicates().reset_index(drop<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="other-adapted-dataframe---made-up-of-books-that-have-been-adapated-as-plays-video-games-novels-etc." class="level4">
<h4 class="anchored" data-anchor-id="other-adapted-dataframe---made-up-of-books-that-have-been-adapated-as-plays-video-games-novels-etc."><em>Other Adapted DataFrame</em> - made up of books that have been adapated as plays, video games, novels, etc.</h4>
<div id="573d90c8" class="cell" data-execution_count="65">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>oth_adap_id <span class="op">=</span> adaptations.loc[adaptations[<span class="st">'TypeCode'</span>] <span class="op">==</span> <span class="dv">3</span>, <span class="st">'BookID'</span>].tolist()</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>oth_adap_name <span class="op">=</span> []</span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> oth_adap_id:</span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> index, book <span class="kw">in</span> books.iterrows():</span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> i <span class="op">==</span> book[<span class="st">'BookID'</span>]:</span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a>      oth_adap_name.append(book[<span class="st">'Title'</span>])</span>
<span id="cb68-8"><a href="#cb68-8" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb68-9"><a href="#cb68-9" aria-hidden="true" tabindex="-1"></a>oth_adap <span class="op">=</span> pd.DataFrame({<span class="st">'BookID'</span>: oth_adap_id, <span class="st">'Title'</span>: oth_adap_name})</span>
<span id="cb68-10"><a href="#cb68-10" aria-hidden="true" tabindex="-1"></a>oth_adap <span class="op">=</span> oth_adap.drop_duplicates().reset_index(drop<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="b.-making-a-function" class="level2">
<h2 class="anchored" data-anchor-id="b.-making-a-function">b. Making a Function</h2>
<p>Instead of coding every trait against every group, we make a function to save time and space. What this function does is take in a dataframe (our groups) and a column (the ‘BookID’ column), and returns the average year, average of average ratings, average of number of ratings, average of pages, and the top three genres of books within a group.</p>
<div id="9a76c725" class="cell" data-execution_count="66">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> top_traits(df, book_id):</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  id_list <span class="op">=</span> df[book_id].tolist()</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>  year_list <span class="op">=</span> []</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>  avg_rating_list <span class="op">=</span> []</span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>  num_rating_list <span class="op">=</span> []</span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>  genre_list <span class="op">=</span> []</span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a>  page_list <span class="op">=</span> []</span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb69-9"><a href="#cb69-9" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> i <span class="kw">in</span> id_list:</span>
<span id="cb69-10"><a href="#cb69-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> index, row <span class="kw">in</span> graphic_novels.iterrows():</span>
<span id="cb69-11"><a href="#cb69-11" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span> i <span class="op">==</span> row[<span class="st">'ID'</span>]:</span>
<span id="cb69-12"><a href="#cb69-12" aria-hidden="true" tabindex="-1"></a>        year_list.append(row[<span class="st">'Year'</span>])</span>
<span id="cb69-13"><a href="#cb69-13" aria-hidden="true" tabindex="-1"></a>        avg_rating_list.append(row[<span class="st">'Avg Rating'</span>])</span>
<span id="cb69-14"><a href="#cb69-14" aria-hidden="true" tabindex="-1"></a>        num_rating_list.append(row[<span class="st">'Number of Ratings'</span>])</span>
<span id="cb69-15"><a href="#cb69-15" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb69-16"><a href="#cb69-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> index, row <span class="kw">in</span> book_genres.iterrows():</span>
<span id="cb69-17"><a href="#cb69-17" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span> i <span class="op">==</span> row[<span class="st">'BookID'</span>]:</span>
<span id="cb69-18"><a href="#cb69-18" aria-hidden="true" tabindex="-1"></a>        genre_list.append(row[<span class="st">'GenreID'</span>])</span>
<span id="cb69-19"><a href="#cb69-19" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb69-20"><a href="#cb69-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> index, row <span class="kw">in</span> issue.iterrows():</span>
<span id="cb69-21"><a href="#cb69-21" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span> i <span class="op">==</span> row[<span class="st">'BookID'</span>]:</span>
<span id="cb69-22"><a href="#cb69-22" aria-hidden="true" tabindex="-1"></a>        page_list.append(row[<span class="st">'Pages'</span>])</span>
<span id="cb69-23"><a href="#cb69-23" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb69-24"><a href="#cb69-24" aria-hidden="true" tabindex="-1"></a>  genre_count <span class="op">=</span> pd.DataFrame(genre_list).value_counts().reset_index()</span>
<span id="cb69-25"><a href="#cb69-25" aria-hidden="true" tabindex="-1"></a>  genre_count.columns <span class="op">=</span> [<span class="st">'GenreType'</span>, <span class="st">'Count'</span>]</span>
<span id="cb69-26"><a href="#cb69-26" aria-hidden="true" tabindex="-1"></a>  genre_count <span class="op">=</span> genre_count.groupby(<span class="st">'Count'</span>).agg(<span class="bu">list</span>).reset_index()</span>
<span id="cb69-27"><a href="#cb69-27" aria-hidden="true" tabindex="-1"></a>  genres <span class="op">=</span> genre_count[genre_count[<span class="st">'Count'</span>] <span class="op">&gt;</span> <span class="dv">1</span>].sort_values(by<span class="op">=</span><span class="st">'Count'</span>, ascending<span class="op">=</span><span class="va">False</span>).reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb69-28"><a href="#cb69-28" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb69-29"><a href="#cb69-29" aria-hidden="true" tabindex="-1"></a>  year <span class="op">=</span> <span class="bu">sum</span>(year_list)<span class="op">/</span><span class="bu">len</span>(year_list)</span>
<span id="cb69-30"><a href="#cb69-30" aria-hidden="true" tabindex="-1"></a>  avg_rating <span class="op">=</span> <span class="bu">sum</span>(avg_rating_list)<span class="op">/</span><span class="bu">len</span>(avg_rating_list)</span>
<span id="cb69-31"><a href="#cb69-31" aria-hidden="true" tabindex="-1"></a>  num_rating <span class="op">=</span> <span class="bu">sum</span>(num_rating_list)<span class="op">/</span><span class="bu">len</span>(num_rating_list)</span>
<span id="cb69-32"><a href="#cb69-32" aria-hidden="true" tabindex="-1"></a>  pages <span class="op">=</span> <span class="bu">sum</span>(page_list)<span class="op">/</span><span class="bu">len</span>(page_list)</span>
<span id="cb69-33"><a href="#cb69-33" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb69-34"><a href="#cb69-34" aria-hidden="true" tabindex="-1"></a>  <span class="cf">return</span> (<span class="bu">round</span>(year, <span class="dv">2</span>),</span>
<span id="cb69-35"><a href="#cb69-35" aria-hidden="true" tabindex="-1"></a>          <span class="bu">round</span>(avg_rating, <span class="dv">2</span>),</span>
<span id="cb69-36"><a href="#cb69-36" aria-hidden="true" tabindex="-1"></a>          <span class="bu">round</span>(num_rating, <span class="dv">2</span>),</span>
<span id="cb69-37"><a href="#cb69-37" aria-hidden="true" tabindex="-1"></a>          <span class="bu">round</span>(pages, <span class="dv">2</span>), </span>
<span id="cb69-38"><a href="#cb69-38" aria-hidden="true" tabindex="-1"></a>          genres.head(<span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="iii.-results" class="level1">
<h1>III. Results</h1>
<section id="applying-the-function" class="level2">
<h2 class="anchored" data-anchor-id="applying-the-function">1. Applying the Function</h2>
<div id="f7cac17f" class="cell" data-execution_count="67">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>adap_traits      <span class="op">=</span> top_traits(adap_books, <span class="st">'BookID'</span>)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>books_traits     <span class="op">=</span> top_traits(books, <span class="st">'BookID'</span>)</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>no_adap_traits   <span class="op">=</span> top_traits(no_adap_books, <span class="st">'BookID'</span>)</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>mult_adap_traits <span class="op">=</span> top_traits(mult_adap, <span class="st">'BookID'</span>)</span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>film_adap_traits <span class="op">=</span> top_traits(film_adap, <span class="st">'BookID'</span>)</span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>tel_adap_traits  <span class="op">=</span> top_traits(tel_adap, <span class="st">'BookID'</span>)</span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>oth_adap_traits  <span class="op">=</span> top_traits(oth_adap, <span class="st">'BookID'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We get a list consisting of the year, average ratings, total ratings, pages, and a dataframe of the top three genres, here is the results of the adapted books group:</p>
<div id="cd567095" class="cell" data-execution_count="68">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>adap_traits</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="68">
<pre><code>(1999.85,
 4.06,
 39679.41,
 295.87,
    Count                                  GenreType
 0     12                                [Superhero]
 1      5                                  [Fantasy]
 2      4  [Memoir , Coming of Age, Science Fiction])</code></pre>
</div>
</div>
<p>Because we want to visualize our results in a graph to better grasp our results, we put all of our results into one big dataframe:</p>
<div id="18809b2a" class="cell" data-execution_count="69">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>traits_df <span class="op">=</span> pd.DataFrame({</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">'Group'</span>:[<span class="st">'All Adapted Books'</span>, <span class="st">'All Books'</span>, <span class="st">'Non-Adapted Books'</span>, <span class="st">'Multiple-Adapted Books'</span>, <span class="st">'Film Adapted Books'</span>, <span class="st">'Television Adapted Books'</span>, <span class="st">'Other Adapted Books'</span>],</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">'Year'</span>:[adap_traits[<span class="dv">0</span>], books_traits[<span class="dv">0</span>], no_adap_traits[<span class="dv">0</span>], mult_adap_traits[<span class="dv">0</span>], film_adap_traits[<span class="dv">0</span>], tel_adap_traits[<span class="dv">0</span>], oth_adap_traits[<span class="dv">0</span>]],</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">'Avg Rating'</span>:[adap_traits[<span class="dv">1</span>], books_traits[<span class="dv">1</span>], no_adap_traits[<span class="dv">1</span>], mult_adap_traits[<span class="dv">1</span>], film_adap_traits[<span class="dv">1</span>], tel_adap_traits[<span class="dv">1</span>], oth_adap_traits[<span class="dv">1</span>]],</span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">'Total Ratings'</span>:[adap_traits[<span class="dv">2</span>], books_traits[<span class="dv">2</span>], no_adap_traits[<span class="dv">2</span>], mult_adap_traits[<span class="dv">2</span>], film_adap_traits[<span class="dv">2</span>], tel_adap_traits[<span class="dv">2</span>], oth_adap_traits[<span class="dv">2</span>]],</span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">'Pages'</span>:[adap_traits[<span class="dv">3</span>], books_traits[<span class="dv">3</span>], no_adap_traits[<span class="dv">3</span>], mult_adap_traits[<span class="dv">3</span>], film_adap_traits[<span class="dv">3</span>], tel_adap_traits[<span class="dv">3</span>], oth_adap_traits[<span class="dv">3</span>]],</span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">'Genres'</span>:[adap_traits[<span class="dv">4</span>], books_traits[<span class="dv">4</span>], no_adap_traits[<span class="dv">4</span>], mult_adap_traits[<span class="dv">4</span>], film_adap_traits[<span class="dv">4</span>], tel_adap_traits[<span class="dv">4</span>], oth_adap_traits[<span class="dv">4</span>]]</span>
<span id="cb73-8"><a href="#cb73-8" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="2fea6388" class="cell" data-execution_count="70">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>traits_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="70">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Group</th>
<th data-quarto-table-cell-role="th">Year</th>
<th data-quarto-table-cell-role="th">Avg Rating</th>
<th data-quarto-table-cell-role="th">Total Ratings</th>
<th data-quarto-table-cell-role="th">Pages</th>
<th data-quarto-table-cell-role="th">Genres</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>All Adapted Books</td>
<td>1999.85</td>
<td>4.06</td>
<td>39679.41</td>
<td>295.87</td>
<td>Count Genr...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>All Books</td>
<td>2003.71</td>
<td>3.92</td>
<td>12409.36</td>
<td>230.00</td>
<td>Count GenreType 0 47 [Litera...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Non-Adapted Books</td>
<td>2004.42</td>
<td>3.90</td>
<td>7416.25</td>
<td>218.10</td>
<td>Count GenreType 0 44 [Litera...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Multiple-Adapted Books</td>
<td>1997.67</td>
<td>4.10</td>
<td>62435.44</td>
<td>432.58</td>
<td>Count GenreType 0 ...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Film Adapted Books</td>
<td>1998.81</td>
<td>4.05</td>
<td>48965.11</td>
<td>298.19</td>
<td>Count ...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>Television Adapted Books</td>
<td>2002.44</td>
<td>4.11</td>
<td>8438.67</td>
<td>341.00</td>
<td>Count GenreType 0 ...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>Other Adapted Books</td>
<td>1999.92</td>
<td>4.08</td>
<td>21834.00</td>
<td>307.90</td>
<td>Count GenreType 0 ...</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Since Genres is saved as a dataframe within a dataframe we must take it out and further flatten it into its own dataframe that way it can be graphed:</p>
<div id="11635143" class="cell" data-execution_count="71">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>sources <span class="op">=</span> [<span class="st">'All Adapted Books'</span>, <span class="st">'All Books'</span>, <span class="st">'Non-Adapted Books'</span>, </span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>           <span class="st">'Multiple-Adapted Books'</span>, <span class="st">'Film Adapted Books'</span>, </span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>           <span class="st">'Television Adapted Books'</span>, <span class="st">'Other Adapted Books'</span>]</span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>genre_traits_df <span class="op">=</span> []</span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, source <span class="kw">in</span> <span class="bu">enumerate</span>(sources):</span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a>    genres <span class="op">=</span> traits_df.loc[i, <span class="st">'Genres'</span>].explode(<span class="st">'GenreType'</span>)</span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a>    genres[<span class="st">'Source'</span>] <span class="op">=</span> source</span>
<span id="cb75-9"><a href="#cb75-9" aria-hidden="true" tabindex="-1"></a>    genre_traits_df.append(genres)</span>
<span id="cb75-10"><a href="#cb75-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-11"><a href="#cb75-11" aria-hidden="true" tabindex="-1"></a>genre_traits_df <span class="op">=</span> pd.concat(genre_traits_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="fab085a8" class="cell" data-execution_count="72">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>genre_traits_df <span class="op">=</span> genre_traits_df.pivot(index<span class="op">=</span><span class="st">'Source'</span>, columns<span class="op">=</span><span class="st">'GenreType'</span>, values<span class="op">=</span><span class="st">'Count'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="graphing-results" class="level2">
<h2 class="anchored" data-anchor-id="graphing-results">2. Graphing Results</h2>
<section id="a.-the-ideal-year" class="level3">
<h3 class="anchored" data-anchor-id="a.-the-ideal-year">a. The Ideal Year</h3>
<div id="95e0f351" class="cell" data-scrolled="true" data-execution_count="73">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>year_plot <span class="op">=</span> traits_df.plot.bar(x<span class="op">=</span><span class="st">'Group'</span>, y<span class="op">=</span><span class="st">'Year'</span>, color<span class="op">=</span><span class="st">'cornflowerblue'</span>, rot<span class="op">=</span><span class="dv">0</span>, figsize<span class="op">=</span>(<span class="dv">16</span>,<span class="dv">4</span>), xlabel<span class="op">=</span><span class="st">'Type of Group'</span>, ylabel<span class="op">=</span><span class="st">'Year'</span>, title<span class="op">=</span><span class="st">'Average Year Book Published per Group of Books'</span>)</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>year_plot.set_ylim(<span class="dv">1995</span>, <span class="dv">2005</span>)</span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>ticks <span class="op">=</span> np.arange(<span class="dv">1995</span>, <span class="dv">2006</span>, <span class="dv">1</span>)</span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>year_plot.set_yticks(ticks)</span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="GraphicNovels_files/figure-html/cell-74-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>The average year published of all books lies around the year 2004.</li>
<li><strong>Books that have been adapted seem to come from books published around or before the year 2000.</strong></li>
<li>Books that have not been adapated on average have been newer releases, at least later than the average of all books.</li>
<li>Books that have received multiple adaptations significantly come from books published before the 2000s, around 1997-1998.</li>
<li>For books within adaptations, television adapated books have been published much later (newer) than film adapted and other adapted books.</li>
</ul>
</section>
<section id="b.-the-ideal-rating-score" class="level3">
<h3 class="anchored" data-anchor-id="b.-the-ideal-rating-score">b. The Ideal Rating Score</h3>
<div id="234e5100" class="cell" data-execution_count="74">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>avg_ratings_plot <span class="op">=</span> traits_df.plot.bar(x<span class="op">=</span><span class="st">'Group'</span>, y<span class="op">=</span><span class="st">'Avg Rating'</span>, color<span class="op">=</span><span class="st">'cornflowerblue'</span>, rot<span class="op">=</span><span class="dv">0</span>, figsize<span class="op">=</span>(<span class="dv">16</span>,<span class="dv">4</span>), xlabel<span class="op">=</span><span class="st">'Type of Group'</span>, ylabel<span class="op">=</span><span class="st">'Average Rating Score'</span>, title<span class="op">=</span><span class="st">'Average Rating Score per Group of Books'</span>)</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>avg_ratings_plot.set_ylim(<span class="fl">3.5</span>, <span class="dv">5</span>)</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="GraphicNovels_files/figure-html/cell-75-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>The average rating of All Books lies just below 4.00.</li>
<li>Non-Adapted Books barely has any difference from the rating score of all books.</li>
<li><strong>Adapted Books perform much better in ratings than all books and non-adapted books, with an average score higher than 4.00</strong>.</li>
<li>Multiple-Adapted Books, Film, telelvision, and other adapted books performed around the same mark of all adapted books, 4.00.</li>
</ul>
</section>
<section id="c.-the-ideal-amount-of-ratings" class="level3">
<h3 class="anchored" data-anchor-id="c.-the-ideal-amount-of-ratings">c.&nbsp;The Ideal Amount of Ratings</h3>
<div id="bd7c6486" class="cell" data-execution_count="75">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>avg_number_plot <span class="op">=</span> traits_df.plot.bar(x<span class="op">=</span><span class="st">'Group'</span>, y<span class="op">=</span><span class="st">'Total Ratings'</span>, color<span class="op">=</span><span class="st">'cornflowerblue'</span>, rot<span class="op">=</span><span class="dv">0</span>, figsize<span class="op">=</span>(<span class="dv">16</span>,<span class="dv">4</span>), xlabel<span class="op">=</span><span class="st">'Type of Group'</span>, ylabel<span class="op">=</span><span class="st">'Average Total of Ratings'</span>, title<span class="op">=</span><span class="st">'Average Total of Ratings per Group of Books'</span>)</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>avg_number_plot.set_ylim(<span class="dv">0</span>, <span class="dv">70000</span>)</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="GraphicNovels_files/figure-html/cell-76-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>All books have an average of around 15,000 entries of ratings.</li>
<li><strong>All Adapted books have a much larger amount of ratings than all books and non-adapted books, with 40,0000 entries</strong></li>
<li>Multiple-Adapted books have the highest amount of ratings with almost 70,000 entires.</li>
<li>Film adapted books have ratings entries around 55,0000.</li>
<li>Television adapated books have surprisingly low amounts of ratings, around the 10,000 mark.</li>
</ul>
</section>
<section id="d.-the-ideal-amount-of-pages" class="level3">
<h3 class="anchored" data-anchor-id="d.-the-ideal-amount-of-pages">d.&nbsp;The Ideal Amount of Pages</h3>
<div id="355bb9b4" class="cell" data-execution_count="76">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>pages_plot <span class="op">=</span> traits_df.plot.bar(x<span class="op">=</span><span class="st">'Group'</span>, y<span class="op">=</span><span class="st">'Pages'</span>, rot<span class="op">=</span><span class="dv">0</span>, figsize<span class="op">=</span>(<span class="dv">16</span>,<span class="dv">4</span>), xlabel<span class="op">=</span><span class="st">'Type of Group'</span>, ylabel<span class="op">=</span><span class="st">'Pages'</span>, color<span class="op">=</span><span class="st">'cornflowerblue'</span>, title<span class="op">=</span><span class="st">'Average Number of Pages per Group of Books'</span>)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>ticks <span class="op">=</span> np.arange(<span class="dv">0</span>, <span class="dv">500</span>, <span class="dv">50</span>)</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>pages_plot.set_yticks(ticks)</span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="GraphicNovels_files/figure-html/cell-77-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>All Books have an average around 250 pages.</li>
<li>Non-adapted books fall just below All book pages.</li>
<li><strong>All Adapted Books are about 50 pages more in length than all books, with an average around 300</strong></li>
<li>Multiple Adapted Books are much higher in length, almost an average of 450 pages.</li>
</ul>
</section>
<section id="e.-the-ideal-genre" class="level3">
<h3 class="anchored" data-anchor-id="e.-the-ideal-genre">e. The Ideal Genre</h3>
<div id="f172598f" class="cell" data-scrolled="true" data-execution_count="77">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>genre_plot <span class="op">=</span> genre_traits_df.plot.bar(figsize<span class="op">=</span>(<span class="dv">16</span>,<span class="dv">4</span>), xlabel<span class="op">=</span><span class="st">'Group'</span>, width <span class="op">=</span> <span class="fl">0.7</span>, rot<span class="op">=</span><span class="dv">0</span>, color<span class="op">=</span>[<span class="st">'navy'</span>, <span class="st">'skyblue'</span>, <span class="st">'aquamarine'</span>, <span class="st">'seagreen'</span>, <span class="st">'lightcoral'</span>, <span class="st">'lightpink'</span>, <span class="st">'cornflowerblue'</span>, <span class="st">'goldenrod'</span>, <span class="st">'powderblue'</span>])</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>ticks <span class="op">=</span> np.arange(<span class="dv">0</span>, <span class="dv">55</span>, <span class="dv">5</span>)</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>genre_plot.set_yticks(ticks)</span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="GraphicNovels_files/figure-html/cell-78-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>All Books and Non-Adapted books have the same top three genres: Literary Fiction, Memoir, and Fantasy.</li>
<li><strong>All Adapted Books top genres are Superhero, Fantasy, and, at a tie, Coming-Of-Age, Memoir, and Science Fiction.</strong></li>
<li>Film Adapted Books have the most variability in genres with the top genres beings: Superhero, Science Fiction, and Action/Adventure, Coming-Of-Age, Crime, Historical Fiction, and Memoir.</li>
<li>Multiple Adapted Books most popular genre is Historical Fiction.</li>
</ul>
</section>
</section>
</section>
<section id="iv.-discussion" class="level1">
<h1>IV. Discussion</h1>
<p>THE RECIPE FOR AN ADAPTATION: - Write a Superhero graphic novel (can substitute with Fantasy, Memoir, Coming-Of-Age, or Science Fiction) - Write at least 295.87 pages - Publish around 1999-2000 - Get at least 39,680 people to read it and rate it. - Have those people rate the book at least 4 out of 5 stars.</p>
<p>The ‘recipe’ above more so defines the average book that has been adapted, and less what it really takes to get a novel adapted. In truth, the recipe is unreplicable, an important part of recipes. For one, it is impossible to go back in time and publish a book. Therefore, it is important to think about the context in which these results and data come from. The graphic novels we are sampling are primarily United States published, English language, adult-oriented books. By only including books that have been published in the English language, the collectors cut out a large portion of untranslated international work that would have likely had more variety in genre and subject matter, as their graphic novels target a predominantly adult audience. It’s also important to note that the data was collected from 2016-2020, and capped published books in 2017. The earliest collected data is from the mid-70s, meaning that there are over 20 years of graphic novels published before the 2000s, and only 17 years after. This creates an obvious bias or skew towards books published in earlier years which affects the rest of the traits that reflect their cultural and societal trends. The earliest form of graphic novels in the U.S. begin with the comics from Marvel, who focus on the superhero genre. In the 60s, they began to extend their themes into longer pieces of work becoming considered graphic ‘novels’ targeted towards an older audience. This resurgence of the genre resulted in a positive feedback loop, where more popularity led to more books being made which resulted in more popularity.</p>
<p>Not only does this make graphic novels’s subject matter, genre, and values biased towards their cultural time, but their publishing year gives them an advantage of additional years to get read and rated across a greater audience and developed into an adaptation. The Walt Disney Production Company’s acquisition of Marvel comics led to the inevitable production of several adaptations of their comics. And the success of these films promoted the originals, which led to more people reading the book and rating it. We need to consider that the high ratings of stars and amount of ratings might be a result of being the original source of a beloved film. Since we have no exact data that lists the books’ scores and entries of ratings before getting adapted, it’s impossible to determine what the numbers that aided them to get adapted are. In fact, there is a large variability between the different adaptations, which leads us to call for uncertainty. Film-adapted books have a much higher total of rating entries with a total of 48,965, than television-adapted books that have a total of 8,438. However, the star ratings show television on top with an average of 4.11 stars and film with a rating of 4.05. Television-adapted books are also the latest published year, 2002, within all adaptations, all of which fall below the year 2000. This may further prove that their lack of entries in ratings is due to their earlier publishing date. Hence, all books published in later or recent years do not statistically perform as well as the earlier publications because they fall victim to their time of publishing and the time this data was collected.</p>
<p>This matter of timing also affects their inclusion of being considered an adaptation in this dataset. On average, it takes about 5-10 years for a film or television series to go into production and eventually get released (Dev-Dorrance). So, for example, if a book had been released in 2016, and got picked up for an adaptation in the same year, their adaptation wouldn’t get released until 2021~2026, and by that time data collection and the entire project would be closed. Looking at the data visualizations that concern all graphic novels, there seems to have been an increase in production of the medium as well as a variety in genre. Non-adapted books have the highest year average of 2004 followed by all books that have an average of 2003. Individual counts show that the most graphic novels were published in 2015, followed by 2012, and 2009. The graph is heavily skewed towards publishing years after the 2000s with a lot of the 1990s books trailing at the end. If we look at the genres of these newer releases, we can see a majority of books written in Literary Fiction, followed by Memoir and Science Fiction, given the fall in popularity of superhero books and films in recent years. Thus, if we fast forward 20 years from now, it’s likely that we will see an increase of those genres in adaptations.</p>
<p><strong><em>However, our results do not completely fail to answer the question…</em></strong></p>
<p>While it is not possible to list exact numbers of pages, ratings, etc. We can look at trends in the graph comparing all books and all adapted books to give a rough estimate that would be ideal. When considering terms like these,</p>
<p>UPDATED RECIPE: - Write a graphic novel in any genre - Write at least 50 pages longer than the average graphic novel. - Publish now (the earlier the better). - Get people to read it and become a popular book. - Have the book be rated higher in quality than the average graphic novel.</p>
<p>*The underlying discovery is that there is a strong importance in writing about subject matters and themes for the time we are living in—reflecting cultural and societal values of the current time. That’s what led Marvel to become so popular as they displayed American heroes winning in a time of war. Exposure is the greatest tool to help one get adapted and following trends or commenting on current cultural and societal issues is a good way to relate to a greater audience. Writing a superhero prohibition graphic novel in 2020 is not likely to relate to an audience and circulate among many, and lacks the relevance to prompt an adaptation (RandomNotes).</p>
<p>In the end, do graphic novels need an adaptation?</p>
<p>No.&nbsp;</p>
<p>They don’t. But it would be nice. When novels or ideas get bought out, authors receive a payout and recognition that cements their hard work among others and themselves. It’s a sort-of honor to get one’s work made into a series or film, or anything really. As someone once said, imitation is the greatest form of flattery. Regardless of adaptation or not, graphic novels are severely underrated and deserve more recognition for the dedication of the writers and illustrators. Just because a book has pictures doesn’t mean we should discount its relevance, the quality of story and writing should be the greatest indicators of whether a book is good or not and deserving of an adaptation.</p>
<section id="works-cited" class="level6">
<h6 class="anchored" data-anchor-id="works-cited">Works Cited</h6>
<p>Connell, Pat. “A Rebuttal to Martin Scorsese’s Comments on Marvel.” The Heights, 24 Nov.&nbsp;2023, www.bcheights.com/2023/11/24/a-rebuttal-to-martin-scorseses-comments-on-marvel/.</p>
<p>Dev-Dorrance. “Page to Screen: How Books Become Movies.” Dorrance Publishing Company, 5 June 2019, www.dorrancepublishing.com/page-to-screen-how-books-become-movies/#:~:text=Movies%20can%20take%20a%20year%20in%20development,director%20is%20offered%20the%20next%20Marvel%20movie.</p>
<p>Luster, Joseph. “Manga Sales in Japan Reached Highest Point in History in 2022.” Otaku USA Magazine, 27 Feb.&nbsp;2023, otakuusamagazine.com/manga-sales-in-japan-reached-highest-point-in-history-in-2022/.</p>
<p>Mwissell. “Graphic Novels Fall Victim to ‘Social Norms’ Too.” Comics Studies, 11 Nov.&nbsp;2022, marywashicomics.net/article/graphic-novels-fall-victim-to-social-norms-too/.</p>
<p>“News for Authors.” Random Notes, authornews.penguinrandomhouse.com/trends-and-cultural-impact-in-graphic-books-novels-memoirs-comics-and-more/.</p>
<p>Park, Ed. “Can You Illustrate Emotional Absence? These Graphic Novels Do.” The New York Times, The New York Times, 31 May 2018, www.nytimes.com/2018/05/31/books/review/nick-drnaso-sabrina.html.</p>
<p>“Persepolis.” Rotten Tomatoes, www.rottentomatoes.com/m/persepolis.</p>
<p>“The Booker’s Big Bang.” New Statesman - The Booker’s Big Bang, web.archive.org/web/20120227193902/www.newstatesman.com/books/2008/10/booker-prize-british-literary.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/sujean8222\.github\.io\/GraphicNovelsBlog\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>